### ISSUE TITLE
Using ntlm causes fatal errors sometimes 

### ISSUE THREAD

**Issue by MStoykov** [loadimpact/k6#1344]
The following fatal error happens sometimes only if ntlm is used.
```
fatal error: concurrent map read and map write

goroutine 210520 [running]:
runtime.throw(0xeac0e9, 0x21)
	/usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc004cc6c58 sp=0xc004cc6c28 pc=0x42ee22
runtime.mapaccess1_faststr(0xe16400, 0xc008f5af30, 0xe98dc6, 0xa, 0xc0076f4170)
	/usr/local/go/src/runtime/map_faststr.go:21 +0x44f fp=0xc004cc6cc8 sp=0xc004cc6c58 pc=0x41268f
github.com/loadimpact/k6/vendor/golang.org/x/net/http2.isConnectionCloseRequest(...)
	/home/alpine/go/src/github.com/loadimpact/k6/vendor/golang.org/x/net/http2/transport.go:2514
github.com/loadimpact/k6/vendor/golang.org/x/net/http2.(*clientConnReadLoop).endStreamError(0xc004cc6fb8, 0xc0076f4140, 0x10a5dc0, 0xc00007c030)
	/home/alpine/go/src/github.com/loadimpact/k6/vendor/golang.org/x/net/http2/transport.go:2148 +0x118 fp=0xc004cc6d38 sp=0xc004cc6cc8 pc=0xa236a8
github.com/loadimpact/k6/vendor/golang.org/x/net/http2.(*clientConnReadLoop).endStream(...)
	/home/alpine/go/src/github.com/loadimpact/k6/vendor/golang.org/x/net/http2/transport.go:2139
github.com/loadimpact/k6/vendor/golang.org/x/net/http2.(*clientConnReadLoop).processData(0xc004cc6fb8, 0xc00911d3e0, 0xc00911d3e0, 0x0)
	/home/alpine/go/src/github.com/loadimpact/k6/vendor/golang.org/x/net/http2/transport.go:2129 +0x2de fp=0xc004cc6e00 sp=0xc004cc6d38 pc=0xa22f5e
github.com/loadimpact/k6/vendor/golang.org/x/net/http2.(*clientConnReadLoop).run(0xc004cc6fb8, 0x0, 0x0)
	/home/alpine/go/src/github.com/loadimpact/k6/vendor/golang.org/x/net/http2/transport.go:1714 +0x4ab fp=0xc004cc6f38 sp=0xc004cc6e00 pc=0xa2087b
github.com/loadimpact/k6/vendor/golang.org/x/net/http2.(*ClientConn).readLoop(0xc006502180)
	/home/alpine/go/src/github.com/loadimpact/k6/vendor/golang.org/x/net/http2/transport.go:1607 +0xa3 fp=0xc004cc6fd8 sp=0xc004cc6f38 pc=0xa1fbc3
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc004cc6fe0 sp=0xc004cc6fd8 pc=0x45c091
created by github.com/loadimpact/k6/vendor/golang.org/x/net/http2.(*Transport).newClientConn
	/home/alpine/go/src/github.com/loadimpact/k6/vendor/golang.org/x/net/http2/transport.go:670 +0x62f
```
This is probably in some regards because https://github.com/Azure/go-ntlmssp/issues/9

**Comment by MStoykov** [comment]
possible way to get ntlm server https://stackoverflow.com/a/48238953/5427244

**Comment by mstoykov** [comment]
This is closed as we haven't had any interest in this and we can't reproduce it.
