### ISSUE TITLE
panic: batches panic :-(

### ISSUE THREAD

**Issue by micsjo** [loadimpact/k6#144]
I get irregular "panic" from k6 when running with batches. Both windows and *nix versions produce the same error, both in k6 version 0.12.1
[loadimpactairv2.zip](https://github.com/loadimpact/k6/files/828110/loadimpactairv2.zip)

```C:\Users\Michael\michael@loadimpact.com\LoadImpact\k6>k6 run --type js loadimpactairv2.js

          /\      |‾‾|  /‾‾/  /‾/
     /\  /  \     |  |_/  /  / /
    /  \/    \    |      |  /  ‾‾\
   /          \   |  |‾\  \ | (_) |
  / __________ \  |__|  \__\ \___/  Welcome to k6 v0.12.1!

  execution: local
     output: -
     script: loadimpactairv2.js (js)

   duration: 10m, iterations: 0
        vus: 1, max: 100

    web ui: http://127.0.0.1:6565/

   running [===================================================>======]    panic: Error: Post http://loadimpactair.guldskeden.se/Pages/Booking: net/http: request canceled

goroutine 561 [running]:
panic(0xb8d800, 0xc064a158e0)
        C:/Program Files (x86)/Go/src/runtime/panic.go:500 +0x1af
github.com/loadimpact/k6/js.throw(0xc0467fd910, 0xaf9620, 0xc064a1b320)
        C:/Users/Michael/AppData/Local/Go/src/github.com/loadimpact/k6/js/util.go:60 +0x12e
github.com/loadimpact/k6/js.JSAPI.HTTPRequest(0xc046cf06e0, 0xc045f2401e, 0x4, 0xc045f24030, 0x30, 0xc0649ef4a0, 0x159, 0xc0645e5900, 0x4f, 0x0)
        C:/Users/Michael/AppData/Local/Go/src/github.com/loadimpact/k6/js/api_http.go:80 +0x1644
github.com/loadimpact/k6/js.JSAPI.BatchHTTPRequest.func1(0xc064a12500, 0xc046cf06e0, 0xc045f2401e, 0x4, 0xc045f24030, 0x30, 0xc0649ef4a0, 0x159, 0xc0645e5900, 0x4f, ...)
        C:/Users/Michael/AppData/Local/Go/src/github.com/loadimpact/k6/js/api_http.go:143 +0xc7
created by github.com/loadimpact/k6/js.JSAPI.BatchHTTPRequest
        C:/Users/Michael/AppData/Local/Go/src/github.com/loadimpact/k6/js/api_http.go:149 +0x47c```

Script to execute attached in zip-file.

**Comment by uppfinnarn** [comment]
Ah, looks like error handling isn't working properly in the spawned goroutines; JS errors are handled through panics with JS objects, which need to be passed back to the main goroutine and re-panic'd there to trigger a JS-side throw.

**Comment by caalle** [comment]
Also getting a `panic error` when having stages that scales down and removes the VU I guess.

```
DEBU[0028] processStages: interpolating...               from=31 to=30]        21s / 1m15s
panic: Error: Get http://test.loadimpact.com/style.css: net/http: request canceled / 1m15s

goroutine 5655 [running]:
panic(0x785cc0, 0xc44e299bc0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/loadimpact/k6/js.throw(0xc4237357b0, 0x6f0720, 0xc44e2a8d20)
	/Users/carl/go/src/github.com/loadimpact/k6/js/util.go:60 +0x127
github.com/loadimpact/k6/js.JSAPI.HTTPRequest(0xc4248f9b80, 0xc422b1ad4e, 0x3, 0xc422b1ad1e, 0x24, 0x0, 0x0, 0xc44e2923aa, 0x2, 0xf067d)
	/Users/carl/go/src/github.com/loadimpact/k6/js/api_http.go:81 +0x1607
github.com/loadimpact/k6/js.JSAPI.BatchHTTPRequest.func1(0xc44e292680, 0xc4248f9b80, 0xc422b1ad4e, 0x3, 0xc422b1ad1e, 0x24, 0x0, 0x0, 0xc44e2923aa, 0x2, ...)
	/Users/carl/go/src/github.com/loadimpact/k6/js/api_http.go:144 +0xc0
created by github.com/loadimpact/k6/js.JSAPI.BatchHTTPRequest
	/Users/carl/go/src/github.com/loadimpact/k6/js/api_http.go:150 +0x475
```
