### ISSUE TITLE
JSON.parse with reviver option cause panic

### ISSUE THREAD

**Issue by n-batrakov** [loadimpact/k6#1552]
`reviver` option in `JSON.parse` causes k6 to panic, no matter what revive function is doing.

## Environment

- k6 version: `k6 v0.26.2 (2020-03-18T11:45:39+0000/v0.26.2-0-g459da79e, go1.13.8, linux/amd64)`
- OS and version: Ubuntu 20.04 LTS

## Expected Behavior

Calling `JSON.parse` with `reviver` option transforms the output with provided function, e.g.

```js
let obj = JSON.parse('{ "a": "foo" }', (k, v) => k === 'a' ? 'bar' : v)
// Outputs: { a: 'bar' }
```

## Actual Behavior

The code above causes panic:

```
panic: interface conversion: goja.Value is goja.valueUndefined, not *goja.Object [recovered]
        panic: interface conversion: goja.Value is goja.valueUndefined, not *goja.Object [recovered]
        panic: interface conversion: goja.Value is goja.valueUndefined, not *goja.Object

goroutine 56 [running]:
github.com/loadimpact/k6/vendor/github.com/dop251/goja.AssertFunction.func1.1(0xc0005f7cd8)
        github.com/loadimpact/k6/vendor/github.com/dop251/goja/runtime.go:1456 +0x98
panic(0xd6d500, 0xc001546cc0)
        runtime/panic.go:679 +0x1b2
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*vm).try.func1(0xc001d4f2b0, 0x0, 0xc0005f7ba8, 0x0, 0x0, 0x0, 0xc0005f7c00)
        github.com/loadimpact/k6/vendor/github.com/dop251/goja/vm.go:373 +0x3b0
panic(0xd6d500, 0xc001546cc0)
        runtime/panic.go:679 +0x1b2
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*Runtime).builtinJSON_reviveWalk(0xc000fe7500, 0xc000f722d0, 0xc0017a0040, 0x10c5b60, 0x1951fb0, 0xc000f72380, 0x0)
        github.com/loadimpact/k6/vendor/github.com/dop251/goja/builtin_json.go:156 +0x5dc
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*Runtime).builtinJSON_reviveWalk(0xc000fe7500, 0xc000f722d0, 0xc0017a0080, 0x10c5b60, 0x1951fb0, 0x0, 0x203000)
        github.com/loadimpact/k6/vendor/github.com/dop251/goja/builtin_json.go:170 +0x1ab
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*Runtime).builtinJSON_parse(0xc000fe7500, 0x10c5980, 0xc0027231c0, 0xc0006d6680, 0x2, 0x8, 0x83e1535f, 0x4508b9c83fc13fbd)
        github.com/loadimpact/k6/vendor/github.com/dop251/goja/builtin_json.go:35 +0x454
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*vm)._nativeCall(0xc001d4f2b0, 0xc0024a2210, 0x2)
        github.com/loadimpact/k6/vendor/github.com/dop251/goja/vm.go:1835 +0x291
github.com/loadimpact/k6/vendor/github.com/dop251/goja.call.exec(0xc000000002, 0xc001d4f2b0)
        github.com/loadimpact/k6/vendor/github.com/dop251/goja/vm.go:1819 +0x4a2
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*vm).run(0xc001d4f2b0)
        github.com/loadimpact/k6/vendor/github.com/dop251/goja/vm.go:289 +0x99
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*funcObject).Call(0xc000641380, 0x10c5fc0, 0x19736e0, 0xc000f72200, 0x1, 0x1, 0x9f9000009f4, 0x9fc000009fc)
        github.com/loadimpact/k6/vendor/github.com/dop251/goja/func.go:130 +0x2cc
github.com/loadimpact/k6/vendor/github.com/dop251/goja.AssertFunction.func1.2()
        github.com/loadimpact/k6/vendor/github.com/dop251/goja/runtime.go:1461 +0x96
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*vm).try(0xc001d4f2b0, 0xc00025cc50, 0x0)
        github.com/loadimpact/k6/vendor/github.com/dop251/goja/vm.go:379 +0x147
github.com/loadimpact/k6/vendor/github.com/dop251/goja.AssertFunction.func1(0x10c5fc0, 0x19736e0, 0xc000f72200, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
        github.com/loadimpact/k6/vendor/github.com/dop251/goja/runtime.go:1460 +0x13a
github.com/loadimpact/k6/js.(*VU).runFn(0xc002603ea0, 0x10b8d40, 0xc001835500, 0xc002047b60, 0x10b8d01, 0xc001ba4900, 0xc000f72200, 0x1, 0x1, 0xc00003c300, ...)
        github.com/loadimpact/k6/js/runner.go:477 +0x35e
github.com/loadimpact/k6/js.(*VU).RunOnce(0xc002603ea0, 0x10b8d40, 0xc001835500, 0x0, 0x0)
        github.com/loadimpact/k6/js/runner.go:427 +0x277
github.com/loadimpact/k6/core/local.(*vuHandle).run(0xc001144540, 0xc000130000, 0xc00003c240, 0xc0000aa540)
        github.com/loadimpact/k6/core/local/local.go:70 +0x152
github.com/loadimpact/k6/core/local.(*Executor).scale.func1(0xc001144540, 0xc0022e67e0, 0xc00003c240, 0xc0000aa540)
        github.com/loadimpact/k6/core/local/local.go:349 +0x4d
created by github.com/loadimpact/k6/core/local.(*Executor).scale
        github.com/loadimpact/k6/core/local/local.go:348 +0x328
```

## Steps to Reproduce the Problem

Run sample script with `k6 run`

```js
export default function main() {
  JSON.parse('{ "a": "foo" }', (k, v) => k === 'a' ? 'bar' : v)
}
```

**Comment by MStoykov** [comment]
Hi, thanks for reporting it, I was able to find it and propose a [minimal fix](https://github.com/dop251/goja/pull/165).
Hopefully, this will be merged soon (or a better fix will be proposed :D ) and we will be able to get it in k6 in a following release. 

Will leave this open and close it with the PR which updates in k6
