### ISSUE TITLE
Test is causing OOM

### ISSUE THREAD

**Issue by pgniewosz** [loadimpact/k6#285]
A test without having any actual load at all 

 ```vus --1```and ```iterations 1```

is reproducible causing OOM on the runtime: 

```bash
        /\      |‾‾|  /‾‾/  /‾/
     /\  /  \     |  |_/  /  / /
    /  \/    \    |      |  /  ‾‾\
   /          \   |  |‾\  \ | (_) |
  / __________ \  |__|  \__\ \___/  Welcome to k6 v0.16.0!
  execution: local
     output: -
     script: - (js)
   duration: 0s, iterations: 1
        vus: 1, max: 1
    web ui: http://0.0.0.0:6565/
fatal error: runtime: out of memory
runtime stack:
runtime.throw(0xb0cff2, 0x16)
        /usr/local/go/src/runtime/panic.go:566 +0x95
runtime.sysMap(0xc424c30000, 0x6f0000, 0x1400, 0xfaf658)
        /usr/local/go/src/runtime/mem_linux.go:219 +0x1d0
runtime.(*mheap).sysAlloc(0xf95a20, 0x6f0000, 0x2d00000001)
        /usr/local/go/src/runtime/malloc.go:407 +0x37a
runtime.(*mheap).grow(0xf95a20, 0x378, 0x0)
        /usr/local/go/src/runtime/mheap.go:726 +0x62
runtime.(*mheap).allocSpanLocked(0xf95a20, 0x378, 0x447140)
        /usr/local/go/src/runtime/mheap.go:630 +0x4f2
runtime.(*mheap).alloc_m(0xf95a20, 0x378, 0x100000000, 0xc400011f9e)
        /usr/local/go/src/runtime/mheap.go:515 +0xe0
runtime.(*mheap).alloc.func1()
        /usr/local/go/src/runtime/mheap.go:579 +0x4b
runtime.systemstack(0x7f67d16aedd8)
        /usr/local/go/src/runtime/asm_amd64.s:314 +0xab
runtime.(*mheap).alloc(0xf95a20, 0x378, 0x10100000000, 0xc420391a70)
        /usr/local/go/src/runtime/mheap.go:580 +0xa0
runtime.largeAlloc(0x6f0000, 0x7f67d16aee01, 0x45ecea)
        /usr/local/go/src/runtime/malloc.go:774 +0x93
runtime.mallocgc.func1()
        /usr/local/go/src/runtime/malloc.go:669 +0x3e
runtime.systemstack(0xc420014000)
        /usr/local/go/src/runtime/asm_amd64.s:298 +0x79
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1079
goroutine 14 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:252 fp=0xc420a10938 sp=0xc420a10930
runtime.mallocgc(0x6f0000, 0xaa2320, 0x1, 0x0)
        /usr/local/go/src/runtime/malloc.go:670 +0x90c fp=0xc420a109d8 sp=0xc420a10938
runtime.growslice(0xaa2320, 0xc4246a0000, 0x1d952, 0x1d955, 0x1d959, 0xafd72d, 0x4, 0xe1a960)
        /usr/local/go/src/runtime/slice.go:131 +0x15e fp=0xc420a10a68 sp=0xc420a109d8
github.com/loadimpact/k6/js/modules/k6/http.(*HTTP).Request(0xfacd70, 0xe16260, 0xc4207e03f0, 0xafd72d, 0x4, 0xe1a960, 0xc42013eda0, 0xc420f332e0, 0x2, 0x2, ...)
        /go/src/github.com/loadimpact/k6/js/modules/k6/http/http.go:261 +0x2e6 fp=0xc420a10b68 sp=0xc420a10a68
github.com/loadimpact/k6/js/modules/k6/http.(*HTTP).Post(0xfacd70, 0xe16260, 0xc4207e03f0, 0xe1a960, 0xc42013eda0, 0xc420f332e0, 0x2, 0x2, 0x0, 0x0, ...)
        /go/src/github.com/loadimpact/k6/js/modules/k6/http/http.go:278 +0x9f fp=0xc420a10be0 sp=0xc420a10b68
runtime.call128(0xc4203910e0, 0xc4227d37d0, 0xc423812d20, 0x4000000058)
        /usr/local/go/src/runtime/asm_amd64.s:481 +0x66 fp=0xc420a10c70 sp=0xc420a10be0
reflect.Value.call(0xab1920, 0xfacd70, 0x1613, 0xb02b4a, 0x9, 0xc4225acfa0, 0x3, 0x3, 0x0, 0xa7bea0, ...)
        /usr/local/go/src/reflect/value.go:434 +0x5c8 fp=0xc420a10fc0 sp=0xc420a10c70
reflect.Value.CallSlice(0xab1920, 0xfacd70, 0x1613, 0xc4225acfa0, 0x3, 0x3, 0x2, 0x2, 0xc420f33300)
        /usr/local/go/src/reflect/value.go:315 +0xa4 fp=0xc420a11028 sp=0xc420a10fc0
github.com/loadimpact/k6/js/common.Bind.func1(0xc420d6e990, 0x2, 0x2, 0xc420d6e990, 0x0, 0x2)
        /go/src/github.com/loadimpact/k6/js/common/bridge.go:169 +0x227 fp=0xc420a11118 sp=0xc420a11028
reflect.callReflect(0xc421c58a20, 0xc420a112d8)
        /usr/local/go/src/reflect/value.go:506 +0x39e fp=0xc420a112b8 sp=0xc420a11118
reflect.makeFuncStub(0xe1a960, 0xc42013eda0, 0xc420f332e0, 0x2, 0x2, 0x0, 0xc420d6e970, 0xc420f332c0, 0xc420a11668, 0x61f008, ...)
        /usr/local/go/src/reflect/asm_amd64.s:17 +0x40 fp=0xc420a112d8 sp=0xc420a112b8
runtime.call64(0xc42060e660, 0xc421c58a20, 0xc420d6e960, 0x2800000030)
        /usr/local/go/src/runtime/asm_amd64.s:480 +0x4c fp=0xc420a11328 sp=0xc420a112d8
reflect.Value.call(0xc4221f5440, 0xc421c58a20, 0x13, 0xafd585, 0x4, 0xc4225ace60, 0x2, 0x3, 0x0, 0x0, ...)
        /usr/local/go/src/reflect/value.go:434 +0x5c8 fp=0xc420a11678 sp=0xc420a11328
reflect.Value.Call(0xc4221f5440, 0xc421c58a20, 0x13, 0xc4225ace60, 0x3, 0x3, 0xc4200101e0, 0x16, 0x0)
        /usr/local/go/src/reflect/value.go:302 +0xa4 fp=0xc420a116e0 sp=0xc420a11678
github.com/dop251/goja.(*Runtime).wrapReflectFunc.func1(0xe1a780, 0xc421c58e00, 0xc420a14ca0, 0x3, 0x12, 0x0, 0x0)
        /go/src/github.com/dop251/goja/runtime.go:1062 +0x859 fp=0xc420a11888 sp=0xc420a116e0
github.com/dop251/goja.(*vm)._nativeCall(0xc420053860, 0xc4228596b0, 0x3)
        /go/src/github.com/dop251/goja/vm.go:1827 +0x2d0 fp=0xc420a11930 sp=0xc420a11888
github.com/dop251/goja.call.exec(0xc400000003, 0xc420053860)
        /go/src/github.com/dop251/goja/vm.go:1808 +0x749 fp=0xc420a119f8 sp=0xc420a11930
github.com/dop251/goja.(*call).exec(0xc42203f818, 0xc420053860)
        <autogenerated>:816 +0x5a fp=0xc420a11a38 sp=0xc420a119f8
github.com/dop251/goja.(*vm).run(0xc420053860)
        /go/src/github.com/dop251/goja/vm.go:288 +0x92 fp=0xc420a11a70 sp=0xc420a11a38
github.com/dop251/goja.(*funcObject).Call(0xc420245ec0, 0xe1adc0, 0xfacd70, 0x0, 0x0, 0x0, 0xc4224c4d00, 0x6)
        /go/src/github.com/dop251/goja/func.go:130 +0x31b fp=0xc420a11b18 sp=0xc420a11a70
github.com/dop251/goja.(*funcObject).Call-fm(0xe1adc0, 0xfacd70, 0x0, 0x0, 0x0, 0xc420a11be0, 0xc420a11bf0)
        /go/src/github.com/dop251/goja/builtin_function.go:120 +0x51 fp=0xc420a11b68 sp=0xc420a11b18
github.com/dop251/goja.AssertFunction.func1.1()
        /go/src/github.com/dop251/goja/runtime.go:1315 +0xbc fp=0xc420a11be0 sp=0xc420a11b68
github.com/dop251/goja.(*vm).try(0xc420053860, 0xc420a11c88, 0x0)
        /go/src/github.com/dop251/goja/vm.go:370 +0x143 fp=0xc420a11c70 sp=0xc420a11be0
github.com/dop251/goja.AssertFunction.func1(0xe1adc0, 0xfacd70, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/dop251/goja/runtime.go:1316 +0xdb fp=0xc420a11cd8 sp=0xc420a11c70
github.com/loadimpact/k6/js.(*VU).RunOnce(0xc420606c80, 0xe161a0, 0xc4220b1440, 0xc421c7c101, 0x13, 0x1d, 0x0, 0x0)
        /go/src/github.com/loadimpact/k6/js/runner.go:187 +0x2aa fp=0xc420a11dc8 sp=0xc420a11cd8
github.com/loadimpact/k6/core/local.(*vuHandle).run(0xc4220b0840, 0xc420048500, 0xc42213ef00, 0xc42213ed80)
        /go/src/github.com/loadimpact/k6/core/local/local.go:60 +0x18d fp=0xc420a11f40 sp=0xc420a11dc8
github.com/loadimpact/k6/core/local.(*Executor).scale.func1(0xc4220b0840, 0xc4200c0c30, 0xc42213ef00, 0xc42213ed80)
        /go/src/github.com/loadimpact/k6/core/local/local.go:267 +0x4d fp=0xc420a11f70 sp=0xc420a11f40
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc420a11f78 sp=0xc420a11f70
created by github.com/loadimpact/k6/core/local.(*Executor).scale
        /go/src/github.com/loadimpact/k6/core/local/local.go:269 +0x28c
goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc4229fb58c)
        /usr/local/go/src/runtime/sema.go:47 +0x30
sync.(*WaitGroup).Wait(0xc4229fb580)
        /usr/local/go/src/sync/waitgroup.go:131 +0x97
main.actionRun(0xc4224ab680, 0x0, 0xc4224ab680)
        /go/src/github.com/loadimpact/k6/run.go:571 +0x200e
gopkg.in/urfave/cli%2ev1.HandleAction(0xa2bc60, 0xb599d8, 0xc4224ab680, 0xc4221f5200, 0x0)
        /go/src/gopkg.in/urfave/cli.v1/app.go:485 +0xd4
gopkg.in/urfave/cli%2ev1.Command.Run(0xafd35d, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0xb0f129, 0x1a, 0x0, ...)
        /go/src/gopkg.in/urfave/cli.v1/command.go:193 +0xb96
gopkg.in/urfave/cli%2ev1.(*App).Run(0xc421ece1a0, 0xc42000c1e0, 0x3, 0x3, 0x0, 0x0)
        /go/src/gopkg.in/urfave/cli.v1/app.go:250 +0x812
main.main()
        /go/src/github.com/loadimpact/k6/main.go:82 +0x5ec
goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1
goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:116 +0x157
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x41
goroutine 7 [chan receive]:
github.com/loadimpact/k6/core.(*Engine).Run.func5(0xc42061b000, 0xc420e984f0, 0xc42061b010, 0xc42213ea80, 0xc42070bb80, 0xc42061aff0, 0xc42061afe0)
        /go/src/github.com/loadimpact/k6/core/engine.go:199 +0xa4
github.com/loadimpact/k6/core.(*Engine).Run(0xc42070bb80, 0xe161a0, 0xc4220b1280, 0x0, 0x0)
        /go/src/github.com/loadimpact/k6/core/engine.go:240 +0xedd
main.actionRun.func2(0xc4229fb580, 0xc42070bb80, 0xe161a0, 0xc4220b1280, 0xc42061af70)
        /go/src/github.com/loadimpact/k6/run.go:495 +0x101
created by main.actionRun
        /go/src/github.com/loadimpact/k6/run.go:499 +0x180b
goroutine 8 [IO wait]:
net.runtime_pollWait(0x7f67d3669ac8, 0x72, 0x0)
        /usr/local/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc422634a00, 0x72, 0xc420033c70, 0xc420012160)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc422634a00, 0xe10de0, 0xc420012160)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).accept(0xc4226349a0, 0x0, 0xe0d9a0, 0xc421c49400)
        /usr/local/go/src/net/fd_unix.go:419 +0x238
net.(*TCPListener).accept(0xc420e98578, 0xc420391a10, 0xc420033d80, 0x558e60)
        /usr/local/go/src/net/tcpsock_posix.go:132 +0x2e
net.(*TCPListener).AcceptTCP(0xc420e98578, 0xc42038e95c, 0xc420033d70, 0x50db80)
        /usr/local/go/src/net/tcpsock.go:209 +0x49
net/http.tcpKeepAliveListener.Accept(0xc420e98578, 0xc4203919e0, 0xa40f60, 0xf7f010, 0xa86fa0)
        /usr/local/go/src/net/http/server.go:2608 +0x2f
net/http.(*Server).Serve(0xc42038e900, 0xe15c20, 0xc420e98578, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:2273 +0x1ce
net/http.(*Server).ListenAndServe(0xc42038e900, 0xc42038e900, 0xc421c49260)
        /usr/local/go/src/net/http/server.go:2219 +0xb4
net/http.ListenAndServe(0xc4229fb5a0, 0xc, 0xe0c9e0, 0xc4203918f0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:2351 +0xa0
github.com/loadimpact/k6/api.ListenAndServe(0xc4229fb5a0, 0xc, 0xc42070bb80, 0x0, 0x0)
        /go/src/github.com/loadimpact/k6/api/server.go:54 +0x224
main.actionRun.func3(0xc4229fb5a0, 0xc, 0xc42070bb80)
        /go/src/github.com/loadimpact/k6/run.go:503 +0x43
created by main.actionRun
        /go/src/github.com/loadimpact/k6/run.go:506 +0x184a
goroutine 9 [select, locked to thread]:
runtime.gopark(0xb5a210, 0x0, 0xaffebf, 0x6, 0x18, 0x2)
        /usr/local/go/src/runtime/proc.go:259 +0x13a
runtime.selectgoImpl(0xc420a1df20, 0x0, 0x18)
        /usr/local/go/src/runtime/select.go:423 +0x1235
runtime.selectgo(0xc420a1df20)
        /usr/local/go/src/runtime/select.go:238 +0x1c
runtime.ensureSigM.func1()
        /usr/local/go/src/runtime/signal1_unix.go:304 +0x2f3
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1
goroutine 13 [select]:
github.com/loadimpact/k6/core/local.(*Executor).Run.func1(0xc42213ef00, 0xc42061b030, 0xc4200c0c30, 0xc42213ed80, 0xc420031d38, 0xc42213ea80)
        /go/src/github.com/loadimpact/k6/core/local/local.go:151 +0x4a6
github.com/loadimpact/k6/core/local.(*Executor).Run(0xc4200c0c30, 0xe161a0, 0xc4220b1380, 0xc42213ea80, 0x0, 0x0)
        /go/src/github.com/loadimpact/k6/core/local/local.go:230 +0xbe0
github.com/loadimpact/k6/core.(*Engine).Run.func4(0xc420e984f0, 0xc42070bb80, 0xe161a0, 0xc4220b1380, 0xc42213ea80, 0xc42061b010)
        /go/src/github.com/loadimpact/k6/core/engine.go:180 +0x5f
created by github.com/loadimpact/k6/core.(*Engine).Run
        /go/src/github.com/loadimpact/k6/core/engine.go:183 +0x7f2
goroutine 24 [semacquire]:
sync.runtime_Semacquire(0xc4200c0c5c)
        /usr/local/go/src/runtime/sema.go:47 +0x30
sync.(*WaitGroup).Wait(0xc4200c0c50)
        /usr/local/go/src/sync/waitgroup.go:131 +0x97
github.com/loadimpact/k6/core/local.(*Executor).Run.func1.1(0xc4200c0c30, 0xc4220c65a0)
        /go/src/github.com/loadimpact/k6/core/local/local.go:145 +0x31
created by github.com/loadimpact/k6/core/local.(*Executor).Run.func1
        /go/src/github.com/loadimpact/k6/core/local/local.go:147 +0x104
goroutine 51948 [runnable]:
net/http.(*Transport).getConn.func2.1(0xc423812840, 0xc4200c0ff0, 0xb59da0)
        /usr/local/go/src/net/http/transport.go:873
created by net/http.(*Transport).getConn.func2
        /usr/local/go/src/net/http/transport.go:878 +0x7a
goroutine 51940 [runnable]:
net/http.setRequestCancel.func4(0x0, 0xc420d72e70, 0xc4220c3b00, 0xc4238120c0)
        /usr/local/go/src/net/http/client.go:328
created by net/http.setRequestCancel
        /usr/local/go/src/net/http/client.go:337 +0x29f
goroutine 51953 [runnable]:
net/http.(*Transport).getConn.func4(0xc4200c0ff0, 0xe16260, 0xc420d6ebd0, 0xc420d6ec30, 0xc423812f00)
        /usr/local/go/src/net/http/transport.go:884
created by net/http.(*Transport).getConn
        /usr/local/go/src/net/http/transport.go:887 +0x398
goroutine 51929 [runnable]:
net/http.(*Transport).getConn.func4(0xc4200c0ff0, 0xe16260, 0xc420d791d0, 0xc420d79230, 0xc4238053e0)
        /usr/local/go/src/net/http/transport.go:884
created by net/http.(*Transport).getConn
        /usr/local/go/src/net/http/transport.go:887 +0x398
goroutine 51930 [runnable]:
net/http.(*Transport).getConn.func2.1(0xc4238053e0, 0xc4200c0ff0, 0xb59da0)
        /usr/local/go/src/net/http/transport.go:873
created by net/http.(*Transport).getConn.func2
        /usr/local/go/src/net/http/transport.go:878 +0x7a
goroutine 51928 [runnable]:
net/http.setRequestCancel.func4(0x0, 0xc420d79200, 0xc4220c36c0, 0xc423805320)
        /usr/local/go/src/net/http/client.go:328
created by net/http.setRequestCancel
        /usr/local/go/src/net/http/client.go:337 +0x29f
goroutine 51943 [runnable]:
net/http.setRequestCancel.func4(0x0, 0xc420d73680, 0xc4220c3c40, 0xc423812420)
        /usr/local/go/src/net/http/client.go:328
created by net/http.setRequestCancel
        /usr/local/go/src/net/http/client.go:337 +0x29f
goroutine 51935 [runnable]:
net/http.(*Transport).getConn.func4(0xc4200c0ff0, 0xe16260, 0xc420d79e60, 0xc420d79f50, 0xc423805aa0)
        /usr/local/go/src/net/http/transport.go:884
created by net/http.(*Transport).getConn
        /usr/local/go/src/net/http/transport.go:887 +0x398
goroutine 51944 [runnable]:
net/http.(*Transport).getConn.func4(0xc4200c0ff0, 0xe16260, 0xc420d73650, 0xc420d736b0, 0xc4238124e0)
        /usr/local/go/src/net/http/transport.go:884
created by net/http.(*Transport).getConn
        /usr/local/go/src/net/http/transport.go:887 +0x398
goroutine 51936 [runnable]:
net/http.(*Transport).getConn.func2.1(0xc423805aa0, 0xc4200c0ff0, 0xb59da0)
        /usr/local/go/src/net/http/transport.go:873
created by net/http.(*Transport).getConn.func2
        /usr/local/go/src/net/http/transport.go:878 +0x7a
goroutine 51937 [runnable]:
net/http.setRequestCancel.func4(0x0, 0xc420d72780, 0xc4220c3a00, 0xc423805d40)
        /usr/local/go/src/net/http/client.go:328
created by net/http.setRequestCancel
        /usr/local/go/src/net/http/client.go:337 +0x29f
goroutine 51938 [runnable]:
net/http.(*Transport).getConn.func4(0xc4200c0ff0, 0xe16260, 0xc420d72750, 0xc420d727b0, 0xc423805e00)
        /usr/local/go/src/net/http/transport.go:884
created by net/http.(*Transport).getConn
        /usr/local/go/src/net/http/transport.go:887 +0x398
goroutine 51933 [runnable]:
net/http.(*Transport).getConn.func2.1(0xc423805740, 0xc4200c0ff0, 0xb59da0)
        /usr/local/go/src/net/http/transport.go:873
created by net/http.(*Transport).getConn.func2
        /usr/local/go/src/net/http/transport.go:878 +0x7a
goroutine 51947 [runnable]:
net/http.(*Transport).getConn.func4(0xc4200c0ff0, 0xe16260, 0xc420d73ec0, 0xc420d73f20, 0xc423812840)
        /usr/local/go/src/net/http/transport.go:884
created by net/http.(*Transport).getConn
        /usr/local/go/src/net/http/transport.go:887 +0x398
goroutine 51931 [runnable]:
net/http.setRequestCancel.func4(0x0, 0xc420d79860, 0xc4220c37c0, 0xc423805680)
        /usr/local/go/src/net/http/client.go:328
created by net/http.setRequestCancel
        /usr/local/go/src/net/http/client.go:337 +0x29f
goroutine 4415 [chan receive]:
github.com/loadimpact/k6/core.(*Engine).Run.func5.1(0xc420e984f0, 0xc42061b010, 0xc42213ea80)
        /go/src/github.com/loadimpact/k6/core/engine.go:193 +0x73
created by github.com/loadimpact/k6/core.(*Engine).Run.func5
        /go/src/github.com/loadimpact/k6/core/engine.go:198 +0x65
goroutine 51950 [runnable]:
net/http.(*Transport).getConn.func4(0xc4200c0ff0, 0xe16260, 0xc420d6e540, 0xc420d6e5d0, 0xc423812ba0)
        /usr/local/go/src/net/http/transport.go:884
created by net/http.(*Transport).getConn
        /usr/local/go/src/net/http/transport.go:887 +0x398
goroutine 51942 [runnable]:
net/http.(*Transport).getConn.func2.1(0xc423812180, 0xc4200c0ff0, 0xb59da0)
        /usr/local/go/src/net/http/transport.go:873
created by net/http.(*Transport).getConn.func2
        /usr/local/go/src/net/http/transport.go:878 +0x7a
goroutine 51941 [runnable]:
net/http.(*Transport).getConn.func4(0xc4200c0ff0, 0xe16260, 0xc420d72d50, 0xc420d72ea0, 0xc423812180)
        /usr/local/go/src/net/http/transport.go:884
created by net/http.(*Transport).getConn
        /usr/local/go/src/net/http/transport.go:887 +0x398
goroutine 51952 [runnable]:
net/http.setRequestCancel.func4(0x0, 0xc420d6ec00, 0xc4220b0480, 0xc423812e40)
        /usr/local/go/src/net/http/client.go:328
created by net/http.setRequestCancel
        /usr/local/go/src/net/http/client.go:337 +0x29f
goroutine 51945 [runnable]:
net/http.(*Transport).getConn.func2.1(0xc4238124e0, 0xc4200c0ff0, 0xb59da0)
        /usr/local/go/src/net/http/transport.go:873
created by net/http.(*Transport).getConn.func2
        /usr/local/go/src/net/http/transport.go:878 +0x7a
goroutine 51932 [runnable]:
net/http.(*Transport).getConn.func4(0xc4200c0ff0, 0xe16260, 0xc420d79830, 0xc420d79890, 0xc423805740)
        /usr/local/go/src/net/http/transport.go:884
created by net/http.(*Transport).getConn
        /usr/local/go/src/net/http/transport.go:887 +0x398
goroutine 51946 [runnable]:
net/http.setRequestCancel.func4(0x0, 0xc420d73ef0, 0xc4220c3dc0, 0xc423812780)
        /usr/local/go/src/net/http/client.go:328
created by net/http.setRequestCancel
        /usr/local/go/src/net/http/client.go:337 +0x29f
goroutine 51954 [runnable]:
net/http.(*Transport).getConn.func2.1(0xc423812f00, 0xc4200c0ff0, 0xb59da0)
        /usr/local/go/src/net/http/transport.go:873
created by net/http.(*Transport).getConn.func2
        /usr/local/go/src/net/http/transport.go:878 +0x7a
goroutine 51939 [runnable]:
net/http.(*Transport).getConn.func2.1(0xc423805e00, 0xc4200c0ff0, 0xb59da0)
        /usr/local/go/src/net/http/transport.go:873
created by net/http.(*Transport).getConn.func2
        /usr/local/go/src/net/http/transport.go:878 +0x7a
goroutine 51951 [runnable]:
net/http.(*Transport).getConn.func2.1(0xc423812ba0, 0xc4200c0ff0, 0xb59da0)
        /usr/local/go/src/net/http/transport.go:873
created by net/http.(*Transport).getConn.func2
        /usr/local/go/src/net/http/transport.go:878 +0x7a
goroutine 51934 [runnable]:
net/http.setRequestCancel.func4(0x0, 0xc420d79e90, 0xc4220c3900, 0xc4238059e0)
        /usr/local/go/src/net/http/client.go:328
created by net/http.setRequestCancel
        /usr/local/go/src/net/http/client.go:337 +0x29f
goroutine 51949 [runnable]:
net/http.setRequestCancel.func4(0x0, 0xc420d6e570, 0xc4220b0340, 0xc423812ae0)
        /usr/local/go/src/net/http/client.go:328
created by net/http.setRequestCancel
        /usr/local/go/src/net/http/client.go:337 +0x29f
~/r/loadimpact                                                       
Add Comment Collap
``` 

My test case looks like this: 

```bash

import http from "k6/http";
import {sleep} from "k6";
import {check} from "k6";

/**
 * POST Request against /coba_resources/resolve
 *
 * @param {string} url - URL of CWS instance.
 * @param {number} resource_ID - Resource ID for multi level resolve.
 * @param {string} configuration string - Resolve a config string against a CoBa resource version.
 * @param {string} requestHeaders - API-Token passed in request header.
 *
 */

export default function() {


    const apiToken = "MYAWESEOMETOKEN2288272"; //API-Token of user loadimpact
    const resourceID = 2; // Resource-ID for Project 213WS (213_807_2015.coba). Retrieve COBA-File from CWS on AWS
    const url = `http://urlblabla.eu-central-1.compute.amazonaws.com/api/v1/coba_resources/${resourceID}/resolve`;
    const configString = JSON.stringify({configuration_string: "", layer_type: ["all"], add_url:"true",
    add_options:"true", resolve_material_schemes_2d: "true"});
    const requestHeaders = {headers: {"Authorization": "Token "  + apiToken }};


  let res = http.post(url,configString,requestHeaders);
  check(res, {
      "is status 200": (res) => res.status === 200,
      "is still status 202": (res) => res.status === 202
  });

  // Poll
    let pollingTimeout = 300000; // value in ms (timeout of 5 minutes)
    let start = new Date().getTime();
    let elapsed = 0;
    while (elapsed < pollingTimeout) {
        res = http.post(url,configString,requestHeaders);
        if (res.status === 200) {
            break;
        }
        sleep(4); // polling request rate
        elapsed = new Date().getTime() - start;
    }
    check(null, {
        "polling succeeded": () => elapsed < pollingTimeout
    });

    // logging statement for debugging purposes
    //console.log(res.body);


};

```

**Comment by robingustafsson** [comment]
@pgniewosz I'm trying to debug this by setting up a mock of the API you're hitting (as I can't reproduce it simply by changing the URL). What is the size of the responses for those POST requests?

**Comment by pgniewosz** [comment]
@robingustafsson, thanks for taking care of this issue. The size of the responses containing the actual data is 571 KB.

**Comment by pgniewosz** [comment]
Do you need samples of a request/response?

**Comment by pgniewosz** [comment]
What I've found so far is that it seems to be the while-loop that for some reason is causing trouble when k6 is about to finish the test. So looks like an issue that goes down into the JS engine we're using. A workaround that I've found to work is to replace the while-loop with a for-loop:

```
// Poll
let pollingTimeout = 300000; // value in ms (timeout of 5 minutes)
let pollingRate = 4; // value in seconds
let pollingAttempts = parseInt(Math.ceil(pollingTimeout / 1000 / pollingRate));
let i = 0;
for (; i < pollingAttempts; i++) {
    res = http.post(url,configString,requestHeaders);
    if (res.status === 200) {
        break;
    }
    sleep(pollingRate); // polling request rate
}
check(null, {
    "polling succeeded": () => i < pollingAttempts
});
```

**Comment by robingustafsson** [comment]
Thanks @pgniewosz for updating the issue. The following script is what I've found so far to be the smallest possible to reproduce the OOM error:

```js
import http from "k6/http";
import {sleep} from "k6";

export let options = {
  vus: 1,
  duration: "3s"
};

export default function() {
  sleep(1);
  while (1) {
      let res = http.get("http://test.loadimpact.com/");
      if (res.status === 200) {
        break;
      }
  }
}
```

I suppose you @liclac is better at digging deeper to find the actual cause.

**Comment by liclac** [comment]
This is interesting. It happens specifically when an iteration is aborted, because what happens under the hood for that is that the `context` is aborted, preventing any further communication with the outside world, sleep() calls, etc. The idea is that in lieu of anything to do, the test should just exit.

I did not consider while (true) loops.

What this does is just enter a busy loop of sending a request, having it immediately aborted for being out-of-context, but generating samples saying so, indefinitely, until it allocates so much memory that the host kills it.

**Comment by liclac** [comment]
Attempting to implement this seems to have uncovered no less than two (2) separate bugs in the JS runtime, one of which is a panic.

https://github.com/dop251/goja/issues/53
https://github.com/dop251/goja/issues/54

**Comment by liclac** [comment]
Done! fb09498
