### ISSUE TITLE
false positive on header response

### ISSUE THREAD

**Issue by aidylewis** [loadimpact/k6#306]
```js
import http from "k6/http";
import { check } from 'k6';

export default function() {
  let res = http.get("https://www.cloudflare.com/");
  check(res, { "seerver": (r) => r.headers[server] === ("cloudflare-nginx")});
}
```

```
ERRO[0001] ReferenceError: server is not defined======================]      200ms / 0s
        at HTTP2 (/Users/lewisa29/projects/k6-load-tests/js/http_2.js:6:70(5))
        at native
        at /Users/lewisa29/projects/k6-load-tests/js/http_2.js:6:22(16)

      done [==========================================================]      200ms / 200ms

    ✓ server
```

HTTP ticked and coloured green. Is the first param a string literal for documentation purposes?

**Comment by liclac** [comment]
Uh, that would be because you probably mean ["server"]

**Comment by aidylewis** [comment]
Ah. yes.

**Comment by aidylewis** [comment]
I am partially sighted after a gang attack, so I do tend to make spelling mistakes from time to time. Many apologies.
