### ISSUE TITLE
Strange error 

### ISSUE THREAD

**Issue by IPeter** [loadimpact/k6#368]
```
          /\      |‾‾|  /‾‾/  /‾/   
     /\  /  \     |  |_/  /  / /   
    /  \/    \    |      |  /  ‾‾\  
   /          \   |  |‾\  \ | (_) | 
  / __________ \  |__|  \__\ \___/ .io

  execution: local--------------------------------------------------]   servertor
     output: -
     script: -

    duration: 20s, iterations: -
         vus: 10,  max: 10

time="2017-11-17T19:38:49Z" level=info msg=Running i=0 t=999.06243ms] starting
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: Panic at 55: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9dc8e1]

goroutine 29 [running]:
github.com/dop251/goja.(*vm).try.func1(0xc42006be10, 0x0, 0xc4233cbc40, 0x0, 0x0, 0x0, 0xc4233cbc98)
	/go/src/github.com/dop251/goja/vm.go:364 +0x4b4
panic(0xb4df00, 0x1244b50)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/loadimpact/k6/js/modules/k6/http.(*HTTP).request.func1(0xc420a9ad00, 0xc4210d2550, 0x1, 0x1, 0xc4214e0340, 0x35)
	/go/src/github.com/loadimpact/k6/js/modules/k6/http/http.go:322 +0xd1
net/http.(*Client).checkRedirect(0xc4213722d0, 0xc420a9ad00, 0xc4210d2550, 0x1, 0x1, 0x0, 0x1)
	/usr/local/go/src/net/http/client.go:411 +0x5a
net/http.(*Client).Do(0xc4213722d0, 0xc4200cbf00, 0xc4213723c0, 0xc4200cbf00, 0xc4213723c0)
	/usr/local/go/src/net/http/client.go:568 +0x918
github.com/loadimpact/k6/js/modules/k6/http.(*HTTP).request(0xc421e21b00, 0x10c41e0, 0xc421337ec0, 0xc4230f3800, 0xc420d5b2c0, 0xc2db69, 0x3, 0x10c8de0, 0xc420ca2e10, 0xc420e09640, ...)
	/go/src/github.com/loadimpact/k6/js/modules/k6/http/http.go:333 +0x7cb
github.com/loadimpact/k6/js/modules/k6/http.(*HTTP).Request(0xc421e21b00, 0x10c41e0, 0xc421337ec0, 0xc2db69, 0x3, 0x10c8de0, 0xc420ca2e10, 0xc420e09640, 0x2, 0x2, ...)
	/go/src/github.com/loadimpact/k6/js/modules/k6/http/http.go:424 +0x11d
github.com/loadimpact/k6/js/modules/k6/http.(*HTTP).Get(0xc421e21b00, 0x10c41e0, 0xc421337ec0, 0x10c8de0, 0xc420ca2e10, 0xc420ca2e40, 0x1, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/loadimpact/k6/js/modules/k6/http/http.go:432 +0x175
reflect.Value.call(0xbcaec0, 0xc421e21b00, 0xe13, 0xc32e53, 0x9, 0xc420f73360, 0x3, 0x3, 0xbba5e0, 0xc420ca2e50, ...)
	/usr/local/go/src/reflect/value.go:434 +0x905
reflect.Value.CallSlice(0xbcaec0, 0xc421e21b00, 0xe13, 0xc420f73360, 0x3, 0x3, 0x194, 0xc423392710, 0x671e98)
	/usr/local/go/src/reflect/value.go:315 +0xa4
github.com/loadimpact/k6/js/common.Bind.func1(0x10c8c00, 0xc421de3fe0, 0xc42222b110, 0x2, 0x3, 0xc42002aa80, 0x7fac5fbe6000)
	/go/src/github.com/loadimpact/k6/js/common/bridge.go:210 +0x967
github.com/dop251/goja.(*vm)._nativeCall(0xc42006be10, 0xc422ebb600, 0x2)
	/go/src/github.com/dop251/goja/vm.go:1824 +0x2ec
github.com/dop251/goja.call.exec(0x2, 0xc42006be10)
	/go/src/github.com/dop251/goja/vm.go:1808 +0x6b3
github.com/dop251/goja.(*call).exec(0xc420780ce8, 0xc42006be10)
	<autogenerated>:1 +0x44
github.com/dop251/goja.(*vm).run(0xc42006be10)
	/go/src/github.com/dop251/goja/vm.go:288 +0x51
github.com/dop251/goja.(*funcObject).Call(0xc4209bc3c0, 0x10c9240, 0x12788e0, 0x0, 0x0, 0x0, 0xc42002aa80, 0xc42001c000)
	/go/src/github.com/dop251/goja/func.go:130 +0x3c8
github.com/dop251/goja.(*funcObject).Call-fm(0x10c9240, 0x12788e0, 0x0, 0x0, 0x0, 0x42a5f9, 0xc42008a0a0)
	/go/src/github.com/dop251/goja/builtin_function.go:120 +0x51
github.com/dop251/goja.AssertFunction.func1.1()
	/go/src/github.com/dop251/goja/runtime.go:1313 +0xb6
github.com/dop251/goja.(*vm).try(0xc42006be10, 0xc423392cb8, 0x0)
	/go/src/github.com/dop251/goja/vm.go:370 +0x119
github.com/dop251/goja.AssertFunction.func1(0x10c9240, 0x12788e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2, 0x2)
	/go/src/github.com/dop251/goja/runtime.go:1312 +0xdd
github.com/loadimpact/k6/js.(*VU).RunOnce(0xc42081c5f0, 0x10c4120, 0xc420dba500, 0x0, 0x10c9100, 0xc4209deb48, 0x10c9100, 0xc4209deb80)
	/go/src/github.com/loadimpact/k6/js/runner.go:214 +0x331
github.com/loadimpact/k6/core/local.(*vuHandle).run(0xc4232e0ec0, 0xc4200709b0, 0xc42242a1e0, 0xc42242a180)
	/go/src/github.com/loadimpact/k6/core/local/local.go:64 +0x1cc
github.com/loadimpact/k6/core/local.(*Executor).scale.func1(0xc4232e0ec0, 0xc422912c60, 0xc42242a1e0, 0xc42242a180)
	/go/src/github.com/loadimpact/k6/core/local/local.go:310 +0x4d
created by github.com/loadimpact/k6/core/local.(*Executor).scale
	/go/src/github.com/loadimpact/k6/core/local/local.go:309 +0x35f
```

I'm using the latest docker image on my 17.10 ubuntu. I get this error at some pages from my site, other pages works well with k6.

**Comment by ppcano** [comment]
@IPeter Could you kindly check if this is the same issue than #369?

**Comment by IPeter** [comment]
@ppcano It's the same issue. Thanks!

**Comment by ppcano** [comment]
Closing in favor of #369
