### ISSUE TITLE
Runtime error thrown: index out of range

### ISSUE THREAD

**Issue by carl-thomas** [loadimpact/k6#512]
I am running this command
`k6 run --vus=2 --duration=10s --out json=results.json identity-server.js`
which runs a test suite which calls a login and then calls 1 api authenticated with the token and 2 unauthenticated without a token. I am outputting this to a json file.
However, I keep getting this error 

```

          /\      |‾‾|  /‾‾/  /‾/   
     /\  /  \     |  |_/  /  / /   
    /  \/    \    |      |  /  ‾‾\  
   /          \   |  |‾\  \ | (_) | 
  / __________ \  |__|  \__\ \___/ .io

  execution: local
     output: json=results.json
     script: identity-server.js

    duration: 10s, iterations: -
         vus: 2,   max: 2

panic: runtime error: index out of range [recovered]================] 10s / 10s
        panic: Panic at 6: runtime error: index out of range [recovered]
        panic: Panic at 6: runtime error: index out of range [recovered]
        panic: Panic at 29: Panic at 6: runtime error: index out of range [recovered]
        panic: Panic at 29: Panic at 6: runtime error: index out of range

goroutine 25 [running]:
github.com/loadimpact/k6/vendor/github.com/dop251/goja.AssertFunction.func1.1(0xc42429fc70)
        /private/tmp/k6-20180215-67700-i3a0nu/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/runtime.go:1407 +0xa2
panic(0x1755dc0, 0xc421453870)
        /usr/local/Cellar/go/1.9.4/libexec/src/runtime/panic.go:491 +0x283
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*vm).try.func1(0xc4200888f0, 0x0, 0xc42429fb78, 0x0, 0x0, 0x0, 0xc42429fbd0)
        /private/tmp/k6-20180215-67700-i3a0nu/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/vm.go:364 +0x4b4
panic(0x1755dc0, 0xc421453860)
        /usr/local/Cellar/go/1.9.4/libexec/src/runtime/panic.go:491 +0x283
github.com/loadimpact/k6/vendor/github.com/dop251/goja.AssertFunction.func1.1(0xc42429f0b8)
        /private/tmp/k6-20180215-67700-i3a0nu/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/runtime.go:1407 +0xa2
panic(0x1755dc0, 0xc421453860)
        /usr/local/Cellar/go/1.9.4/libexec/src/runtime/panic.go:491 +0x283
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*vm).try.func1(0xc4200888f0, 0x2, 0xc42429efc0, 0x6, 0x0, 0x0, 0xc42429f018)
        /private/tmp/k6-20180215-67700-i3a0nu/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/vm.go:364 +0x4b4
panic(0x176a360, 0x1eb2f90)
        /usr/local/Cellar/go/1.9.4/libexec/src/runtime/panic.go:491 +0x283
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*SrcFile).Position(0xc421dfd580, 0xa57, 0xa57, 0x45)
        /private/tmp/k6-20180215-67700-i3a0nu/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/srcfile.go:42 +0x107
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*stackFrame).position(0xc42226bf80, 0xc42001d03a, 0x0)
        /private/tmp/k6-20180215-67700-i3a0nu/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/runtime.go:115 +0x56
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*stackFrame).write(0xc42226bf80, 0xc422c543f0)
        /private/tmp/k6-20180215-67700-i3a0nu/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/runtime.go:130 +0x93
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*Exception).writeShortStack(0xc42226bf40, 0xc422c543f0)
        /private/tmp/k6-20180215-67700-i3a0nu/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/runtime.go:197 +0x83
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*InterruptedError).Error(0xc42226bf40, 0x94, 0x1)
        /private/tmp/k6-20180215-67700-i3a0nu/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/runtime.go:182 +0xf0
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*Runtime).NewGoError(0xc42158e000, 0x1d277a0, 0xc42226bf40, 0xc42226bf40)
        /private/tmp/k6-20180215-67700-i3a0nu/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/runtime.go:362 +0x35
github.com/loadimpact/k6/js/common.Throw(0xc42158e000, 0x1d277a0, 0xc42226bf40)
        /private/tmp/k6-20180215-67700-i3a0nu/src/github.com/loadimpact/k6/js/common/util.go:42 +0x5b
github.com/loadimpact/k6/js/common.Bind.func1(0x1d37600, 0x1ee6e40, 0xc4242a27a0, 0x2, 0x28, 0xc4222cae00, 0x6)
        /private/tmp/k6-20180215-67700-i3a0nu/src/github.com/loadimpact/k6/js/common/bridge.go:217 +0xaa2
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*vm)._nativeCall(0xc4200888f0, 0xc423921b80, 0x2)
        /private/tmp/k6-20180215-67700-i3a0nu/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/vm.go:1826 +0x2ec
github.com/loadimpact/k6/vendor/github.com/dop251/goja.call.exec(0x2, 0xc4200888f0)
        /private/tmp/k6-20180215-67700-i3a0nu/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/vm.go:1810 +0x6b3
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*call).exec(0xc420fe0224, 0xc4200888f0)
        <autogenerated>:1 +0x44
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*vm).run(0xc4200888f0)
        /private/tmp/k6-20180215-67700-i3a0nu/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/vm.go:288 +0x51
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*funcObject).Call(0xc4246d4540, 0x1d37600, 0x1ee6e40, 0x0, 0x0, 0x0, 0xc42429f158, 0xc420024600)
        /private/tmp/k6-20180215-67700-i3a0nu/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/func.go:130 +0x3c8
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*funcObject).Call-fm(0x1d37600, 0x1ee6e40, 0x0, 0x0, 0x0, 0x102a809, 0xc420159c30)
        /private/tmp/k6-20180215-67700-i3a0nu/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/builtin_function.go:120 +0x51
github.com/loadimpact/k6/vendor/github.com/dop251/goja.AssertFunction.func1.2()
        /private/tmp/k6-20180215-67700-i3a0nu/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/runtime.go:1412 +0xb6
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*vm).try(0xc4200888f0, 0xc42429f030, 0x0)
        /private/tmp/k6-20180215-67700-i3a0nu/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/vm.go:370 +0x119
github.com/loadimpact/k6/vendor/github.com/dop251/goja.AssertFunction.func1(0x1d37600, 0x1ee6e40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /private/tmp/k6-20180215-67700-i3a0nu/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/runtime.go:1411 +0x12e
github.com/loadimpact/k6/js/modules/k6.(*K6).Group(0x1ee7180, 0x1d32460, 0xc422dccff0, 0xc4209c35c5, 0xf, 0xc421ba1480, 0x0, 0x0, 0x0, 0x0)
        /private/tmp/k6-20180215-67700-i3a0nu/src/github.com/loadimpact/k6/js/modules/k6/k6.go:68 +0x193
reflect.Value.call(0x178e900, 0x1ee7180, 0xa13, 0x184e2ac, 0x4, 0xc423e0efa0, 0x3, 0x3, 0x1772980, 0xc421ba1480, ...)
        /usr/local/Cellar/go/1.9.4/libexec/src/reflect/value.go:434 +0x905
reflect.Value.Call(0x178e900, 0x1ee7180, 0xa13, 0xc423e0efa0, 0x3, 0x3, 0x0, 0x17af8e0, 0x1)
        /usr/local/Cellar/go/1.9.4/libexec/src/reflect/value.go:302 +0xa4
github.com/loadimpact/k6/js/common.Bind.func1(0x1d37600, 0x1ee6e40, 0xc4242a2740, 0x2, 0x2e, 0xc4222cadc0, 0x6)
        /private/tmp/k6-20180215-67700-i3a0nu/src/github.com/loadimpact/k6/js/common/bridge.go:212 +0xb13
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*vm)._nativeCall(0xc4200888f0, 0xc423921ad0, 0x2)
        /private/tmp/k6-20180215-67700-i3a0nu/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/vm.go:1826 +0x2ec
github.com/loadimpact/k6/vendor/github.com/dop251/goja.call.exec(0x2, 0xc4200888f0)
        /private/tmp/k6-20180215-67700-i3a0nu/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/vm.go:1810 +0x6b3
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*call).exec(0xc420fe0320, 0xc4200888f0)
        <autogenerated>:1 +0x44
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*vm).run(0xc4200888f0)
        /private/tmp/k6-20180215-67700-i3a0nu/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/vm.go:288 +0x51
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*funcObject).Call(0xc420b1da40, 0x1d37600, 0x1ee6e40, 0x0, 0x0, 0x0, 0x0, 0xc420024600)
        /private/tmp/k6-20180215-67700-i3a0nu/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/func.go:130 +0x3c8
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*funcObject).Call-fm(0x1d37600, 0x1ee6e40, 0x0, 0x0, 0x0, 0x102a809, 0xc4226dd4c0)
        /private/tmp/k6-20180215-67700-i3a0nu/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/builtin_function.go:120 +0x51
github.com/loadimpact/k6/vendor/github.com/dop251/goja.AssertFunction.func1.2()
        /private/tmp/k6-20180215-67700-i3a0nu/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/runtime.go:1412 +0xb6
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*vm).try(0xc4200888f0, 0xc42429fbe8, 0x0)
        /private/tmp/k6-20180215-67700-i3a0nu/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/vm.go:370 +0x119
github.com/loadimpact/k6/vendor/github.com/dop251/goja.AssertFunction.func1(0x1d37600, 0x1ee6e40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /private/tmp/k6-20180215-67700-i3a0nu/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/runtime.go:1411 +0x12e
github.com/loadimpact/k6/js.(*VU).RunOnce(0xc421d76620, 0x1d323a0, 0xc42251e080, 0x0, 0x1c, 0x20, 0x0, 0x0)
        /private/tmp/k6-20180215-67700-i3a0nu/src/github.com/loadimpact/k6/js/runner.go:265 +0x536
github.com/loadimpact/k6/core/local.(*vuHandle).run(0xc422737140, 0xc420090a50, 0xc4236280c0, 0xc423628060)
        /private/tmp/k6-20180215-67700-i3a0nu/src/github.com/loadimpact/k6/core/local/local.go:64 +0x1cc
github.com/loadimpact/k6/core/local.(*Executor).scale.func1(0xc422737140, 0xc4218bc6c0, 0xc4236280c0, 0xc423628060)
        /private/tmp/k6-20180215-67700-i3a0nu/src/github.com/loadimpact/k6/core/local/local.go:315 +0x4d
created by github.com/loadimpact/k6/core/local.(*Executor).scale
        /private/tmp/k6-20180215-67700-i3a0nu/src/github.com/loadimpact/k6/core/local/local.go:314 +0x35f
```

Sometimes it reaches 10s and sometimes ~8-9s before this is thrown. If I run it without the --out it succeeds with no issues.

Update: This does not happen when omitting the --duration.

**Comment by luizbafilho** [comment]
Hi @carl-thomas sorry the delay, but I'm gonna be working on this. Would it be possible for you to share the script you are using it? 

By looking only at the stack tracer I'm not being able to figure out what is happening.

**Comment by luizbafilho** [comment]
Closing due inactivity. If you face this issue again, please reopen it.
