### ISSUE TITLE
Specifying "Options" before "Post" causes runtime error in script

### ISSUE THREAD

**Issue by kiwipedro** [loadimpact/k6#598]
Recorded an HAR file
Converted it to a .js script
This grouped calls into <pre>http.batch()</pre>

When running script received this error:

<pre>
panic: TypeError: Value is not an object: [object ------------------] 0 / 1i

goroutine 579 [running]:
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*Runtime).typeErrorResult(0xc04d8c7800, 0x1198401, 0xc04bed2ee8, 0x2, 0x2)
        /Users/robin/Projects/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/runtime.go:274 +0x7d
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*Runtime).toCallee(0xc04d8c7800, 0x1196f60, 0xc045603190, 0x0)
        /Users/robin/Projects/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/vm.go:463 +0x1f0
github.com/loadimpact/k6/vendor/github.com/dop251/goja.call.exec(0x1, 0xc045e83450)
        /Users/robin/Projects/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/vm.go:1797 +0x8a
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*call).exec(0xc04560aa3c, 0xc045e83450)
        <autogenerated>:1 +0x4b
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*vm).run(0xc045e83450)
        /Users/robin/Projects/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/vm.go:288 +0x58
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*funcObject).Call(0xc04b31e780, 0x1196d80, 0xc0483ca780, 0x0, 0x0, 0x0, 0xc046389db0, 0xc04bcc98e0)
        /Users/robin/Projects/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/func.go:130 +0x3cf
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*funcObject).Call-fm(0x1196d80, 0xc0483ca780, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/robin/Projects/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/builtin_function.go:120 +0x58
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*baseObject).tryPrimitive(0xc0491d01e0, 0xc9e3d3, 0x8, 0xc04bed3980, 0xbac340)
        /Users/robin/Projects/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/object.go:432 +0x11d
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*baseObject).toPrimitiveString(0xc0491d01e0, 0xc04bed3998, 0xc04bed3988)
        /Users/robin/Projects/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/object.go:457 +0x4b
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*Object).String(0xc0483ca780, 0xc04cd26000, 0xc04bed3980)
        /Users/robin/Projects/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/value.go:627 +0x3e
github.com/loadimpact/k6/js/modules/k6/http.(*HTTP).request(0xc0433159e0, 0x11920c0, 0xc04d0b24e0, 0xc04d8c7800, 0xc04cfc81e0, 0xc044b26848, 0x7, 0xc04a220600, 0xc04bf0d176, 0x31, ...)
        /Users/robin/Projects/go/src/github.com/loadimpact/k6/js/modules/k6/http/http_request.go:160 +0x4cc0
github.com/loadimpact/k6/js/modules/k6/http.(*HTTP).Batch.func1(0xc045e7c920, 0xc046374940, 0xc04a220600, 0xc04bf0d176, 0x31, 0xc04bf0d176, 0x31, 0xc0433159e0, 0x11920c0, 0xc04d0b24e0, ...)
        /Users/robin/Projects/go/src/github.com/loadimpact/k6/js/modules/k6/http/http_request.go:589 +0x18b
created by github.com/loadimpact/k6/js/modules/k6/http.(*HTTP).Batch
        /Users/robin/Projects/go/src/github.com/loadimpact/k6/js/modules/k6/http/http_request.go:580 +0x9c7
</pre>

In the login call the original script had Options and its associated Post like this:

<pre>
		 { "method": "options",
			"url": "https://#####/Config/Token",
			"params": {
				"headers": {
					"Access-Control-Request-Method": "POST",
					"Origin": "#####",
					"Accept-Encoding": "gzip, deflate, br",
					"Host": "dev-api.rewarderplatform.com",
					"Accept-Language": "en-GB,en-US;q=0.9,en;q=0.8",
					"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36",
					"Accept": "*/*",
					"Connection": "keep-alive",
					"Access-Control-Request-Headers": "authorization"
				}
			}
		} , { "method": "post",
			"url": "https://#####/Config/Token",
			"body": {
				"grant_type": "password",
				"username": ######,
				"password": ######
			},
			"params": {
				"headers": {
					"Origin": "https://######",
					"Accept-Encoding": "gzip, deflate, br",
					"Host": "dev-api.rewarderplatform.com",
					"Accept-Language": "en-GB,en-US;q=0.9,en;q=0.8",
					"Authorization": "Bearer null",
					"Content-Type": "application/x-www-form-urlencoded",
					"Accept": "application/json, text/plain, */*",
					"Referer": "https://#####",
					"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36",
					"Connection": "keep-alive",
					"Content-Length": "64"
				}
			}
		},
</pre>

Swapped these around and no more error

<pre>
		{ "method": "post",
			"url": "https://#####/Config/Token",
			"body": {
				"grant_type": "password",
				"username": ######,
				"password": ######
			},
			"params": {
				"headers": {
					"Origin": "https://######",
					"Accept-Encoding": "gzip, deflate, br",
					"Host": "dev-api.rewarderplatform.com",
					"Accept-Language": "en-GB,en-US;q=0.9,en;q=0.8",
					"Authorization": "Bearer null",
					"Content-Type": "application/x-www-form-urlencoded",
					"Accept": "application/json, text/plain, */*",
					"Referer": "https://#####",
					"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36",
					"Connection": "keep-alive",
					"Content-Length": "64"
				}
			}
		},{
			"method": "options",
			"url": "https://#####/Config/Token",
			"params": {
				"headers": {
					"Access-Control-Request-Method": "POST",
					"Origin": "#####",
					"Accept-Encoding": "gzip, deflate, br",
					"Host": "dev-api.rewarderplatform.com",
					"Accept-Language": "en-GB,en-US;q=0.9,en;q=0.8",
					"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36",
					"Accept": "*/*",
					"Connection": "keep-alive",
					"Access-Control-Request-Headers": "authorization"
				}
			}
		}

</pre>

**Comment by kiwipedro** [comment]
Update on this - on further testing with longer script, the error occurred even with the options block after the post.   Removed the options (associated with the post block) and worked ok

**Comment by kiwipedro** [comment]
Further further update - this is nothing to do with just options related to POSTs.  e.g. using scaling up to 5 VUs any options statement present will eventually yield a runtime error.  And the error comes in many flavours - has a data type "NaN" and now this

<pre>
panic: runtime error: index out of range----------------------------] 26.1s / 1m0s

goroutine 2518 [running]:
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*vm).run(0xc04593a340)
        /Users/robin/Projects/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/vm.go:288 +0x191
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*funcObject).Call(0xc04ec0c0c0, 0x1196d80, 0xc043d2f200, 0x0, 0x0, 0x0, 0xc04ba5d3f0, 0xc04cb74540)
        /Users/robin/Projects/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/func.go:130 +0x3cf
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*funcObject).Call-fm(0x1196d80, 0xc043d2f200, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/robin/Projects/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/builtin_function.go:120 +0x58
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*baseObject).tryPrimitive(0xc04daed2c0, 0xc9e3d3, 0x8, 0xc043555980, 0xbac340)
        /Users/robin/Projects/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/object.go:432 +0x11d
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*baseObject).toPrimitiveString(0xc04daed2c0, 0xc043555998, 0xc043555988)
        /Users/robin/Projects/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/object.go:457 +0x4b
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*Object).String(0xc043d2f200, 0xc04ceb0ba0, 0xc043555980)
        /Users/robin/Projects/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/value.go:627 +0x3e
github.com/loadimpact/k6/js/modules/k6/http.(*HTTP).request(0xc044f72c60, 0x11920c0, 0xc04c84b530, 0xc048d71080, 0xc045804f00, 0xc04d7e3a97, 0x7, 0xc049989200, 0xc04e0c58c2, 0x47, ...)
        /Users/robin/Projects/go/src/github.com/loadimpact/k6/js/modules/k6/http/http_request.go:160 +0x4cc0
github.com/loadimpact/k6/js/modules/k6/http.(*HTTP).Batch.func1(0xc043984b98, 0xc04de84220, 0xc049989200, 0xc04e0c58c2, 0x47, 0xc04e0c58c2, 0x47, 0xc044f72c60, 0x11920c0, 0xc04c84b530, ...)
        /Users/robin/Projects/go/src/github.com/loadimpact/k6/js/modules/k6/http/http_request.go:589 +0x18b
created by github.com/loadimpact/k6/js/modules/k6/http.(*HTTP).Batch
        /Users/robin/Projects/go/src/github.com/loadimpact/k6/js/modules/k6/http/http_request.go:580 +0x9c7

</pre>

**Comment by antekresic** [comment]
Here is the minimum issue reproduction script:

```
import { group } from 'k6';
import http from 'k6/http';

export default function() {

	group("test", function() {
		let req, res;
		req = [{
			"method": "options",
			"url": "http://test.loadimpact.com/",
			"params": {
				"headers": {
				}
			}
		},{
			"method": "options",
			"url": "http://test.loadimpact.com/",
			"params": {
				"headers": {
				}
			}
		}];
		res = http.batch(req);
	});

}
```

Looks like the issue is sending slices to goroutines in a loop:
https://github.com/loadimpact/k6/blob/master/js/modules/k6/http/http_request.go#L545
https://github.com/loadimpact/k6/blob/master/js/modules/k6/http/http_request.go#L589

They use the same underlying array so when the main goroutine starts appending stuff, it interferes with the goroutine sending the previous request.

Should be trivial to fix by copying `args` so it uses a different internal array.
