### ISSUE TITLE
Unable to send raw binary file.

### ISSUE THREAD

**Issue by Eeems** [loadimpact/k6#626]
```javascript
import http from 'k6/http';
const zipFile = open('./file.zip', 'b');

export default function(){
    http.post('http://example.com/upload', zipFile);
};
```

Will result in the following error:
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: Panic at 92: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: Panic at 92: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: Panic at 6: Panic at 92: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: Panic at 6: Panic at 92: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xa65fdf]

goroutine 23 [running]:
github.com/loadimpact/k6/vendor/github.com/dop251/goja.AssertFunction.func1.1(0xc421743c88)
        /go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/runtime.go:1407 +0xa2
panic(0xb8cfc0, 0xc42111d070)
        /usr/local/go/src/runtime/panic.go:491 +0x283
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*vm).try.func1(0xc4219ab520, 0x0, 0xc421743b90, 0x0, 0x0, 0x0, 0xc421743be8)
        /go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/vm.go:364 +0x4b4
panic(0xb8cfc0, 0xc42111d060)
        /usr/local/go/src/runtime/panic.go:491 +0x283
github.com/loadimpact/k6/vendor/github.com/dop251/goja.AssertFunction.func1.1(0xc4217430e0)
        /go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/runtime.go:1407 +0xa2
panic(0xb8cfc0, 0xc42111d060)
        /usr/local/go/src/runtime/panic.go:491 +0x283
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*vm).try.func1(0xc4219ab520, 0x2, 0xc421742fe8, 0x6, 0x0, 0x0, 0xc421743040)
        /go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/vm.go:364 +0x4b4
panic(0xba1e40, 0x130efe0)
        /usr/local/go/src/runtime/panic.go:491 +0x283
github.com/loadimpact/k6/js/modules/k6/http.requestContainsFile(0xc4216df830, 0x1193380)
        /go/src/github.com/loadimpact/k6/js/modules/k6/http/http_request.go:632 +0x9f
github.com/loadimpact/k6/js/modules/k6/http.(*HTTP).request(0xc422dfa6c0, 0x118e3c0, 0xc423bdcba0, 0xc422fded80, 0xc42242d400, 0xc8da50, 0x4, 0xc421dbee00, 0xc422b865a0, 0x56, ...)
        /go/src/github.com/loadimpact/k6/js/modules/k6/http/http_request.go:111 +0x4d6b
github.com/loadimpact/k6/js/modules/k6/http.(*HTTP).Request(0xc422dfa6c0, 0x118e3c0, 0xc423bdcba0, 0xc8da50, 0x4, 0x1193560, 0xc4216e66d0, 0xc421a1ae40, 0x2, 0x2, ...)
        /go/src/github.com/loadimpact/k6/js/modules/k6/http/http_request.go:99 +0x208
github.com/loadimpact/k6/js/modules/k6/http.(*HTTP).Post(0xc422dfa6c0, 0x118e3c0, 0xc423bdcba0, 0x1193560, 0xc4216e66d0, 0xc421a1ae40, 0x2, 0x2, 0x0, 0x0, ...)
        /go/src/github.com/loadimpact/k6/js/modules/k6/http/http_request.go:72 +0x9f
```

Upon digging into the code I believe it's because [js/modules/k6/http/http_request.go#L109](https://github.com/loadimpact/k6/blob/master/js/modules/k6/http/http_request.go#L109) will incorrectly think that a binary file is actually something that can be parsed into form data.

**Comment by na--** [comment]
Take a look at the [documentation about uploading files](https://docs.k6.io/docs/file-data-filename-contenttype) and the example there:
```js
import http from "k6/http";

let binFile = open("/path/to/file.bin", "b");

export default function() {
  var data = {
    field: "this is a standard form field",
    file: http.file(binFile, "test.bin")
  };
  var res = http.post("https://example.com/upload", data);
}
```

You have to pass the result of `open()` through `http.file()` and then include its result in a JS object as the second argument of `http.post()` (so you could send multiple files and data values simultaneously)

**Comment by na--** [comment]
I wrongly closed this since I didn't understand what you meant... it became clearer once I read your comments in slack, so I'm reopening this and tagging it as a bug. Example code:
```js
import http from "k6/http";

let someStrFile = open("./test.js");
let someBinFile = open("./test.tar.gz", "b");

export default function () {
    console.log(http.post("https://httpbin.org/post", someStrFile).body)
    console.log(http.post("https://httpbin.org/post", someBinFile).body)
}
```
The first `http.post()` works as you'd expect, but the second one doesn't, for no good reason.

**Comment by Eeems** [comment]
> I wrongly closed this since I didn't understand what you meant... it became clearer once I read your comments in slack, so I'm reopening this and tagging it as a bug.

No problem :) Believe me, I spent way too long on this before realizing it wasn't my code that was at fault.

It seems to be a fairly simple fix, at least from what I can understand of the Go code from never actually using it before.

I've had to work around this by setting up a C# microservice that will handle doing that web call for me. Not ideal, but time constraints require it.

**Comment by rynomad** [comment]
Ran into this same issue. Not super familiar with Go as a language, but adding this extra check on line 109  got us back in business; the exportTo function was coercing the byte array (slice?) into a string mapped object with the byte values as keys and the values as all nil's.

    if args[0].ExportType().String() != "[]uint8" && rt.ExportTo(args[0], &data) == nil {

**Comment by na--** [comment]
Hm, because of [this](https://github.com/dop251/goja/blob/master/runtime.go#L935-L936) I'm wondering if just using `args[0].Export()` and then Go's normal type [assertion](https://tour.golang.org/methods/15)/[switches](https://tour.golang.org/methods/16) wouldn't also work. I'll try that because if it works, it should be much faster than `ExportType()` and `ExportTo()`.

**Comment by na--** [comment]
Quick update: briefly tested my hunch for `val.Export()` and it seems like it will work for fixing this bug in a more performant and readable manner (by using simple type assertions vs. heavy use of reflection).

The problem is that while I was testing, I found another bug relating to request bodies and `http.batch()`. Running:
```js
http.batch([
  //...
  {
    method: "POST",
    url: "http://httpbin.org/post",
    test: "test1",
    body: "test2",
  }
]);
```
Would actually send `test1` as the body.

So right now I'm considering doing a bigger refactoring and bug-fixing session that involves:
- fixing the original bug with binary files in this issue
- fixing the new bug with request bodies and `http.batch()` that I found
- fixing other `http.batch()` issues, including a probable data race (https://github.com/loadimpact/k6/issues/598) - I'm almost positive that the same parts of the code are responsible
- accomplishing a big part of this planned refactoring: https://github.com/loadimpact/k6/issues/574

**Comment by rynomad** [comment]
thanks for the rundown! I figured there must be a better way to tackle it, just not so well versed in Golang myself.
