### ISSUE TITLE
Problem with redirects?

### ISSUE THREAD

**Issue by robingustafsson** [loadimpact/k6#67]
When I run this simple script:

```js
import sleep from "k6";
import http from "k6/http";

export let options = {
    vus: 1
};

export default function() {
    http.get("http://httpbin.org/cookies/set?k2=v2&k1=v1");
    sleep(1);
};
```

it fails miserably with:

```
ERRO[0006] Error: Get /cookies: stopped after 0 redirects             ]      200ms / 10s
    at <native code>
    at request (k6/http.js:91:22)
    at get (k6/http.js:103:9)
    at /Users/robin/.../cookies.js:9:5
```

Why does it fail at 0 redirects?

**Comment by uppfinnarn** [comment]
Fixed by #5a5b04b33a585eb194ab04d45df4e2d57cae4bf4 btw
