### ISSUE TITLE
k6 doesn't properly anonymize archives

### ISSUE THREAD

**Issue by na--** [loadimpact/k6#819]
When creating archives (i.e. when running the `k6 cloud` and `k6 arrchive` commands), k6 tries to anonymize the usernames in any paths that are `open()`-ed or imported: https://github.com/loadimpact/k6/blob/5788beef154b31f95ea8c6da5e86521b6fa07f6a/lib/archive.go#L38-L50

The problem comes from the fact that any file paths in the archives will be anonymized, but the paths in the actual `open("/home/username/file.json")` and `import test from "/home/my_other_username/superlib.js` won't... 

Example script:
```js
import mylib from "/home/user/mylib.js";

var someData = open("/home/user/data.json");

var username = "user" // Can't anonymize that without some strong AI or a magical JS parser :/ ...
var someMoreData = open("/home/" + username + "/data.json");

var theJoyOfJS = eval("open(['/home', 'user', 'data.json'].join('/'))");

export default function () {
    console.log(JSON.stringify(mylib));
    console.log(someData);
    console.log(someMoreData);
    console.log(theJoyOfJS);
}
```

As you might have deduced from the above example, I don't think this is fixable and we should just give up on the whole username anonymization idea...

The produced `archive.tar` file from running `k6 archive` on the above script results in a file that has a `data` file (i.e. the script entrypoint) exactly the same as the script above (no anonymization at all) and a tar file that looks like this (via `tar --list --file archive.tar`):
```  
metadata.json
data
scripts
scripts/_
scripts/_/home
scripts/_/home/nobody
scripts/_/home/nobody/mylib.js
files
files/_
files/_/home
files/_/home/nobody
files/_/home/nobody/data.json
```

This doesn't work, and what's more, `k6 run archive.tar` fails a panic, which is another bug in and of itself:
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: Panic at 29: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: Panic at 29: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x6d97f5]

goroutine 1 [running]:
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*Runtime).RunProgram.func1(0xc4231a2af8)
	/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/runtime.go:880 +0x99
panic(0xbeb880, 0xc42307db20)
	/usr/lib/go/src/runtime/panic.go:502 +0x229
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*vm).try.func1(0xc4202d8d00, 0x0, 0xc4231a29f0, 0x0, 0x0, 0x0, 0xc4231a2a48)
	/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/vm.go:364 +0x45c
panic(0xc03940, 0x14cd250)
	/usr/lib/go/src/runtime/panic.go:502 +0x229
github.com/loadimpact/k6/vendor/github.com/spf13/afero.ReadFile(0x0, 0x0, 0xc420228714, 0x13, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/loadimpact/k6/vendor/github.com/spf13/afero/ioutil.go:65 +0x45
github.com/loadimpact/k6/loader.Load(0x0, 0x0, 0xc4200364e0, 0x25, 0xc420228714, 0x13, 0x0, 0xc4231a21b8, 0x411cc9)
	/go/src/github.com/loadimpact/k6/loader/loader.go:100 +0x3ff
github.com/loadimpact/k6/js.(*InitContext).requireFile(0xc420c22780, 0xc420228714, 0x13, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/loadimpact/k6/js/initcontext.go:135 +0x648
github.com/loadimpact/k6/js.(*InitContext).Require(0xc420c22780, 0xc420228714, 0x13, 0x0, 0x0)
	/go/src/github.com/loadimpact/k6/js/initcontext.go:97 +0xe7
reflect.callMethod(0xc42112e3c0, 0xc4231a2340)
	/usr/lib/go/src/reflect/value.go:663 +0x181
reflect.methodValueCall(0xc420228714, 0x13, 0x0, 0x0, 0xc4231a2620, 0x4b24e9, 0xc42112e330, 0xc42112e3c0, 0xc4208d1ac0, 0x1000000020, ...)
	/usr/lib/go/src/reflect/asm_amd64.s:29 +0x33
reflect.Value.call(0xbd5da0, 0xc42112e3c0, 0x13, 0xd13721, 0x4, 0xc4208d1aa0, 0x1, 0x1, 0x0, 0x0, ...)
	/usr/lib/go/src/reflect/value.go:447 +0x969
reflect.Value.Call(0xbd5da0, 0xc42112e3c0, 0x13, 0xc4208d1aa0, 0x1, 0x1, 0xc42307da80, 0x98, 0x0)
	/usr/lib/go/src/reflect/value.go:308 +0xa4
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*Runtime).wrapReflectFunc.func1(0xe95b00, 0x1501960, 0xc4222c2220, 0x1, 0x1e, 0x7, 0x0)
	/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/runtime.go:1153 +0x8c4
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*vm)._nativeCall(0xc4202d8d00, 0xc4208cd550, 0x1)
	/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/vm.go:1826 +0x2ae
github.com/loadimpact/k6/vendor/github.com/dop251/goja.call.exec(0x1, 0xc4202d8d00)
	/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/vm.go:1810 +0x51d
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*vm).run(0xc4202d8d00)
	/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/vm.go:288 +0x51
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*vm).(github.com/loadimpact/k6/vendor/github.com/dop251/goja.run)-fm()
	/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/vm.go:375 +0x2a
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*vm).try(0xc4202d8d00, 0xc4231a2a50, 0x0)
	/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/vm.go:370 +0x10c
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*vm).runTry(0xc4202d8d00, 0xe1eee0)
	/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/vm.go:375 +0x46
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*Runtime).RunProgram(0xc42136e480, 0xc4215cf020, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/runtime.go:891 +0x1c2
github.com/loadimpact/k6/js.(*Bundle).instantiate(0xc42175f600, 0xc42136e480, 0xc420c22780, 0xc422b1e6ab, 0x1)
	/go/src/github.com/loadimpact/k6/js/bundle.go:262 +0x472
github.com/loadimpact/k6/js.(*Bundle).Instantiate(0xc42175f600, 0xbbb600, 0x0, 0x0)
	/go/src/github.com/loadimpact/k6/js/bundle.go:210 +0x15b
github.com/loadimpact/k6/js.(*Runner).newVU(0xc420ce1040, 0xc421ee8300, 0xc734e0, 0x462301, 0xc421faad40)
	/go/src/github.com/loadimpact/k6/js/runner.go:115 +0x46
github.com/loadimpact/k6/js.(*Runner).NewVU(0xc420ce1040, 0xc421ee8300, 0xc420b2db50, 0x1, 0xc420ac89b0, 0xc420c22230)
	/go/src/github.com/loadimpact/k6/js/runner.go:106 +0x35
github.com/loadimpact/k6/core/local.(*Executor).SetVUsMax(0xc420b2db00, 0x1, 0x0, 0x0)
	/go/src/github.com/loadimpact/k6/core/local/local.go:528 +0x34e
github.com/loadimpact/k6/core.NewEngine(0xe97420, 0xc420b2db00, 0x0, 0x1, 0x0, 0x1, 0x0, 0x0, 0x0, 0x1, ...)
	/go/src/github.com/loadimpact/k6/core/engine.go:86 +0x174
github.com/loadimpact/k6/cmd.glob..func11(0x14d8520, 0xc42056c4d0, 0x1, 0x1, 0x0, 0x0)
	/go/src/github.com/loadimpact/k6/cmd/run.go:182 +0xa7b
github.com/loadimpact/k6/vendor/github.com/spf13/cobra.(*Command).execute(0x14d8520, 0xc42056c4a0, 0x1, 0x1, 0x14d8520, 0xc42056c4a0)
	/go/src/github.com/loadimpact/k6/vendor/github.com/spf13/cobra/command.go:762 +0x468
github.com/loadimpact/k6/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x14d82c0, 0x52, 0xc420576180, 0xc4205ce000)
	/go/src/github.com/loadimpact/k6/vendor/github.com/spf13/cobra/command.go:852 +0x30a
github.com/loadimpact/k6/vendor/github.com/spf13/cobra.(*Command).Execute(0x14d82c0, 0xc420287f78, 0x405d8c)
	/go/src/github.com/loadimpact/k6/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/loadimpact/k6/cmd.Execute()
	/go/src/github.com/loadimpact/k6/cmd/root.go:87 +0x31
main.main()
	/go/src/github.com/loadimpact/k6/main.go:28 +0x20
```

So... I think we should:
- disable that usename anonymization since apparently it has never worked and I don't see how we can make it work properly (t.e. by modifying the script as well as the file paths)
- actually use the `NormalizeAndAnonymizePath` (after removing `homeDirRE`) when we open/import files (when we `run` archives), since it's very likely that the other two regular expressions may also cause issues with the changed file paths...
- fix the panic - k6 shlouldn't panic, even if an archive file is wrong somehow
- test all of those things...

**Comment by MStoykov** [comment]
If we are actually going to run NormalizeAndAnonymizePath on each open than we can keep the anonymizations. 

The bigger problem I have seen is that if you only open files during iterations or setup than that won't be seen when an archive is made and it won't be added to archive. 

My current plan is to actually keep the anonymization and remove it only if there are more problems found at later time
