### ISSUE TITLE
runtime error: invalid memory address during test execution

### ISSUE THREAD

**Issue by electric** [loadimpact/k6#825]
I'm getting the following error while running a test. I can reliably reproduce it with 400+ VU's but the same test runs fine with ~200 VU's.

The test does a few things - visit a web page, log in, view another page, then click a link which should result in a redirect header.

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]s
	panic: Panic at 0: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: Panic at 0: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: Panic at 7: Panic at 0: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: Panic at 7: Panic at 0: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: Panic at 7: Panic at 7: Panic at 0: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: Panic at 7: Panic at 7: Panic at 0: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1471732]
```

**Comment by MStoykov** [comment]
Hm this looks bad. This though doesn't look like a full stack. Given the 400+ VUs I would guess you wouldn't give us the script in order to test it ourself.
Could you compile from master and after that run 
```
GOTRACEBACK=all k6 run path/to/script.js
```

And than paste the whole trace here :).

p.s. I edited your message - to get multiple line preformated text you need it to start with 3(three) '`' and end with the same

**Comment by electric** [comment]
Sorry, must've forgot to copy the whole trace :D here it is in all it's glory:

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: Panic at 0: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: Panic at 0: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: Panic at 7: Panic at 0: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: Panic at 7: Panic at 0: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: Panic at 7: Panic at 7: Panic at 0: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: Panic at 7: Panic at 7: Panic at 0: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1471732]

goroutine 87 [running]:
github.com/loadimpact/k6/vendor/github.com/dop251/goja.AssertFunction.func1.1(0xc0670b9d38)
	/private/tmp/k6-20180917-46753-y0pqeg/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/runtime.go:1407 +0x9b
panic(0x181c520, 0xc067a46110)
	/usr/local/Cellar/go/1.11/libexec/src/runtime/panic.go:513 +0x1b9
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*vm).try.func1(0xc0041d1930, 0x0, 0xc0670b9c40, 0x0, 0x0, 0x0, 0xc0670b9c98)
	/private/tmp/k6-20180917-46753-y0pqeg/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/vm.go:364 +0x459
panic(0x181c520, 0xc067a46100)
	/usr/local/Cellar/go/1.11/libexec/src/runtime/panic.go:513 +0x1b9
github.com/loadimpact/k6/vendor/github.com/dop251/goja.AssertFunction.func1.1(0xc0670b92a0)
	/private/tmp/k6-20180917-46753-y0pqeg/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/runtime.go:1407 +0x9b
panic(0x181c520, 0xc067a46100)
	/usr/local/Cellar/go/1.11/libexec/src/runtime/panic.go:513 +0x1b9
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*vm).try.func1(0xc0041d1930, 0x3, 0xc0670b91a8, 0x9, 0x0, 0x0, 0xc0670b9200)
	/private/tmp/k6-20180917-46753-y0pqeg/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/vm.go:364 +0x459
panic(0x181c520, 0xc067a460f0)
	/usr/local/Cellar/go/1.11/libexec/src/runtime/panic.go:513 +0x1b9
github.com/loadimpact/k6/vendor/github.com/dop251/goja.AssertFunction.func1.1(0xc0670b8808)
	/private/tmp/k6-20180917-46753-y0pqeg/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/runtime.go:1407 +0x9b
panic(0x181c520, 0xc067a460f0)
	/usr/local/Cellar/go/1.11/libexec/src/runtime/panic.go:513 +0x1b9
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*vm).try.func1(0xc0041d1930, 0x6, 0xc0670b8710, 0x11, 0x0, 0x0, 0xc0670b8768)
	/private/tmp/k6-20180917-46753-y0pqeg/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/vm.go:364 +0x459
panic(0x182f320, 0x230b4a0)
	/usr/local/Cellar/go/1.11/libexec/src/runtime/panic.go:513 +0x1b9
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*vm).run(0xc0041d1930)
	/private/tmp/k6-20180917-46753-y0pqeg/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/vm.go:288 +0x82
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*funcObject).Call(0xc087912240, 0x1b01640, 0x233f840, 0x0, 0x0, 0x0, 0x7fb18abb0f0119d1, 0xc0670b8668)
	/private/tmp/k6-20180917-46753-y0pqeg/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/func.go:130 +0x29e
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*funcObject).Call-fm(0x1b01640, 0x233f840, 0x0, 0x0, 0x0, 0xc0670b8738, 0xc092fe2278)
	/private/tmp/k6-20180917-46753-y0pqeg/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/builtin_function.go:120 +0x48
github.com/loadimpact/k6/vendor/github.com/dop251/goja.AssertFunction.func1.2()
	/private/tmp/k6-20180917-46753-y0pqeg/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/runtime.go:1412 +0x96
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*vm).try(0xc0041d1930, 0xc0670b8780, 0x0)
	/private/tmp/k6-20180917-46753-y0pqeg/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/vm.go:370 +0x10c
github.com/loadimpact/k6/vendor/github.com/dop251/goja.AssertFunction.func1(0x1b01640, 0x233f840, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/k6-20180917-46753-y0pqeg/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/runtime.go:1411 +0x10d
github.com/loadimpact/k6/js/modules/k6.(*K6).Group(0x233fb30, 0x1afa480, 0xc05a349d40, 0xc001f055d9, 0x14, 0xc070a6ff80, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/k6-20180917-46753-y0pqeg/src/github.com/loadimpact/k6/js/modules/k6/k6.go:76 +0x164
reflect.Value.call(0x186e8e0, 0x233fb30, 0xa13, 0x1935b51, 0x4, 0xc06dbe3cc0, 0x3, 0x3, 0xc070a6ff80, 0x17c0940, ...)
	/usr/local/Cellar/go/1.11/libexec/src/reflect/value.go:447 +0x449
reflect.Value.Call(0x186e8e0, 0x233fb30, 0xa13, 0xc06dbe3cc0, 0x3, 0x3, 0x0, 0x8, 0x18fa300)
	/usr/local/Cellar/go/1.11/libexec/src/reflect/value.go:308 +0xa4
github.com/loadimpact/k6/js/common.Bind.func1(0x1b01640, 0x233f840, 0xc077d789f0, 0x2, 0x33, 0x0, 0x0)
	/private/tmp/k6-20180917-46753-y0pqeg/src/github.com/loadimpact/k6/js/common/bridge.go:212 +0xc5c
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*vm)._nativeCall(0xc0041d1930, 0xc0594bb970, 0x2)
	/private/tmp/k6-20180917-46753-y0pqeg/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/vm.go:1826 +0x264
github.com/loadimpact/k6/vendor/github.com/dop251/goja.call.exec(0x2, 0xc0041d1930)
	/private/tmp/k6-20180917-46753-y0pqeg/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/vm.go:1810 +0x4d7
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*vm).run(0xc0041d1930)
	/private/tmp/k6-20180917-46753-y0pqeg/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/vm.go:288 +0x5d
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*funcObject).Call(0xc087912180, 0x1b01640, 0x233f840, 0x0, 0x0, 0x0, 0x7fb18abb0f0119d1, 0xc0670b9100)
	/private/tmp/k6-20180917-46753-y0pqeg/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/func.go:130 +0x29e
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*funcObject).Call-fm(0x1b01640, 0x233f840, 0x0, 0x0, 0x0, 0xc0670b91d0, 0xc092fe2278)
	/private/tmp/k6-20180917-46753-y0pqeg/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/builtin_function.go:120 +0x48
github.com/loadimpact/k6/vendor/github.com/dop251/goja.AssertFunction.func1.2()
	/private/tmp/k6-20180917-46753-y0pqeg/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/runtime.go:1412 +0x96
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*vm).try(0xc0041d1930, 0xc0670b9218, 0x0)
	/private/tmp/k6-20180917-46753-y0pqeg/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/vm.go:370 +0x10c
github.com/loadimpact/k6/vendor/github.com/dop251/goja.AssertFunction.func1(0x1b01640, 0x233f840, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/k6-20180917-46753-y0pqeg/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/runtime.go:1411 +0x10d
github.com/loadimpact/k6/js/modules/k6.(*K6).Group(0x233fb30, 0x1afa480, 0xc05a349d40, 0xc000968ab8, 0x16, 0xc070a6fec0, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/k6-20180917-46753-y0pqeg/src/github.com/loadimpact/k6/js/modules/k6/k6.go:76 +0x164
reflect.Value.call(0x186e8e0, 0x233fb30, 0xa13, 0x1935b51, 0x4, 0xc06dbe3b80, 0x3, 0x3, 0xc070a6fec0, 0x17c0940, ...)
	/usr/local/Cellar/go/1.11/libexec/src/reflect/value.go:447 +0x449
reflect.Value.Call(0x186e8e0, 0x233fb30, 0xa13, 0xc06dbe3b80, 0x3, 0x3, 0x0, 0x8, 0x18fa300)
	/usr/local/Cellar/go/1.11/libexec/src/reflect/value.go:308 +0xa4
github.com/loadimpact/k6/js/common.Bind.func1(0x1b01640, 0x233f840, 0xc077d78970, 0x2, 0x3b, 0x0, 0x0)
	/private/tmp/k6-20180917-46753-y0pqeg/src/github.com/loadimpact/k6/js/common/bridge.go:212 +0xc5c
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*vm)._nativeCall(0xc0041d1930, 0xc0594bb810, 0x2)
	/private/tmp/k6-20180917-46753-y0pqeg/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/vm.go:1826 +0x264
github.com/loadimpact/k6/vendor/github.com/dop251/goja.call.exec(0x2, 0xc0041d1930)
	/private/tmp/k6-20180917-46753-y0pqeg/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/vm.go:1810 +0x4d7
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*vm).run(0xc0041d1930)
	/private/tmp/k6-20180917-46753-y0pqeg/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/vm.go:288 +0x5d
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*funcObject).Call(0xc0060249c0, 0x1b01640, 0x233f840, 0xc0680606d0, 0x1, 0x1, 0xc0670b9c00, 0x203016)
	/private/tmp/k6-20180917-46753-y0pqeg/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/func.go:130 +0x29e
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*funcObject).Call-fm(0x1b01640, 0x233f840, 0xc0680606d0, 0x1, 0x1, 0x1013bc6, 0x1013ec2)
	/private/tmp/k6-20180917-46753-y0pqeg/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/builtin_function.go:120 +0x48
github.com/loadimpact/k6/vendor/github.com/dop251/goja.AssertFunction.func1.2()
	/private/tmp/k6-20180917-46753-y0pqeg/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/runtime.go:1412 +0x96
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*vm).try(0xc0041d1930, 0xc0670b9cb0, 0x0)
	/private/tmp/k6-20180917-46753-y0pqeg/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/vm.go:370 +0x10c
github.com/loadimpact/k6/vendor/github.com/dop251/goja.AssertFunction.func1(0x1b01640, 0x233f840, 0xc0680606d0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/k6-20180917-46753-y0pqeg/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/runtime.go:1411 +0x10d
github.com/loadimpact/k6/js.(*VU).runFn(0xc0046f1560, 0x1afa3c0, 0xc06d9882c0, 0xc00301f020, 0xc002c75aa0, 0xc0680606d0, 0x1, 0x1, 0x1b01640, 0x1058400, ...)
	/private/tmp/k6-20180917-46753-y0pqeg/src/github.com/loadimpact/k6/js/runner.go:380 +0x32a
github.com/loadimpact/k6/js.(*VU).RunOnce(0xc0046f1560, 0x1afa3c0, 0xc06d9882c0, 0x0, 0x1)
	/private/tmp/k6-20180917-46753-y0pqeg/src/github.com/loadimpact/k6/js/runner.go:346 +0x195
github.com/loadimpact/k6/core/local.(*vuHandle).run(0xc0068911c0, 0xc0000c2a00, 0xc049458600, 0xc0000407e0)
	/private/tmp/k6-20180917-46753-y0pqeg/src/github.com/loadimpact/k6/core/local/local.go:70 +0x152
github.com/loadimpact/k6/core/local.(*Executor).scale.func1(0xc0068911c0, 0xc0002c45a0, 0xc049458600, 0xc0000407e0)
	/private/tmp/k6-20180917-46753-y0pqeg/src/github.com/loadimpact/k6/core/local/local.go:360 +0x4d
created by github.com/loadimpact/k6/core/local.(*Executor).scale
	/private/tmp/k6-20180917-46753-y0pqeg/src/github.com/loadimpact/k6/core/local/local.go:359 +0x32b
```

**Comment by electric** [comment]
Okay, for whatever reason I can't seem to reproduce this using the version compiled from master, but I _can_ still reproduce it using the version installed from brew, despite both installed versions being version v0.22.1

Thoughts?

**Comment by MStoykov** [comment]
the master only says it's v0.22.1 it's actually like 90 commits ahead so there is good chance we have fixed this either by accident or on purpose.

Given the error I think I will need to take a look at the script you are running if that is possible :). Otherwise I doubt I will be able to guess what in the group call you are making is panicing k6

**Comment by MStoykov** [comment]
Apparently we have fixed this in some of the commits so I am closing it. If you can still reproduce it I would like if you can provide a small script reproducing the problem @electric , if possible :)
