### ISSUE TITLE
Typed arrays cause goja to panic

### ISSUE THREAD

**Issue by na--** [loadimpact/k6#873]
It's most likely a goja bug, but if we have the following k6 script:

```js
import http from "k6/http";

export function setup() {
    var buffer = new ArrayBuffer(8);
    var typedArr = new Uint8Array(buffer, 1, 4);
    typedArr[3] = 123;
    console.log(typedArr); // this works

    // This panics
    http.post("https://httpbingo.org/post", typedArr);

    // This also panics
    return { arr: typedArr };
}

export default function (data) {
    // ...
}
```

The `http.post("https://httpbingo.org/post", typedArr);` will cause the following panic:
```
panic: Cannot export valueProperty [recovered]
	panic: Panic at 30: Cannot export valueProperty [recovered]
	panic: Panic at 30: Cannot export valueProperty

goroutine 53 [running]:
github.com/loadimpact/k6/vendor/github.com/dop251/goja.AssertFunction.func1.1(0xc420b8b360)
	/home/user/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/runtime.go:1407 +0x99
panic(0xbec900, 0xc420de4340)
	/usr/lib/golang/src/runtime/panic.go:502 +0x229
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*vm).try.func1(0xc42009ac30, 0x0, 0xc420b8b268, 0x0, 0x0, 0x0, 0xc420b8b2c0)
	/home/user/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/vm.go:364 +0x45c
panic(0xbbd240, 0xe84200)
	/usr/lib/golang/src/runtime/panic.go:502 +0x229
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*valueProperty).Export(0xc421ad99e0, 0x1, 0xe96ca0)
	/home/user/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/value.go:478 +0x39
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*baseObject).export(0xc4230a3bd0, 0xc420806287, 0x1a)
	/home/user/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/object.go:517 +0x1a1
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*Object).Export(0xc420b21c00, 0xc4230384d0, 0xc420339280)
	/home/user/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/value.go:700 +0x34
github.com/loadimpact/k6/js/modules/k6/http.(*HTTP).Request(0xc4200ae240, 0xe90040, 0xc421ad9590, 0xd14b55, 0x4, 0xe96d40, 0xc4230384d0, 0xc420de4290, 0x1, 0x1, ...)
	/home/user/go/src/github.com/loadimpact/k6/js/modules/k6/http/http_request.go:109 +0x269
github.com/loadimpact/k6/js/modules/k6/http.(*HTTP).Post(0xc4200ae240, 0xe90040, 0xc421ad9590, 0xe96d40, 0xc4230384d0, 0xc420de4290, 0x1, 0x1, 0x0, 0x0, ...)
	/home/user/go/src/github.com/loadimpact/k6/js/modules/k6/http/http_request.go:80 +0x9f
reflect.Value.call(0xcc2f80, 0xc4200ae240, 0x2213, 0xd19bdc, 0x9, 0xc420f62190, 0x3, 0x3, 0xc89ca0, 0xc420de42a0, ...)
	/usr/lib/golang/src/reflect/value.go:447 +0x969
reflect.Value.CallSlice(0xcc2f80, 0xc4200ae240, 0x2213, 0xc420f62190, 0x3, 0x3, 0x194, 0xc420f5e210, 0xc420b8af50)
	/usr/lib/golang/src/reflect/value.go:321 +0xa4
github.com/loadimpact/k6/js/common.Bind.func1(0xe96b60, 0xc420b21360, 0xc4218acc70, 0x2, 0x37, 0xe96b60, 0x0)
	/home/user/go/src/github.com/loadimpact/k6/js/common/bridge.go:210 +0x896
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*vm)._nativeCall(0xc42009ac30, 0xc420f5e210, 0x2)
	/home/user/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/vm.go:1826 +0x2ae
github.com/loadimpact/k6/vendor/github.com/dop251/goja.call.exec(0x2, 0xc42009ac30)
	/home/user/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/vm.go:1810 +0x51d
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*vm).run(0xc42009ac30)
	/home/user/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/vm.go:288 +0x51
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*funcObject).Call(0xc422d84b40, 0xe971a0, 0x1505940, 0xc422d83de0, 0x1, 0x1, 0x4, 0x40bf1f)
	/home/user/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/func.go:130 +0x336
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*funcObject).Call-fm(0xe971a0, 0x1505940, 0xc422d83de0, 0x1, 0x1, 0xc420b8b250, 0xd865ca44)
	/home/user/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/builtin_function.go:120 +0x51
github.com/loadimpact/k6/vendor/github.com/dop251/goja.AssertFunction.func1.2()
	/home/user/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/runtime.go:1412 +0x9f
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*vm).try(0xc42009ac30, 0xc420b8b2d8, 0x0)
	/home/user/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/vm.go:370 +0x10c
github.com/loadimpact/k6/vendor/github.com/dop251/goja.AssertFunction.func1(0xe971a0, 0x1505940, 0xc422d83de0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
	/home/user/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/runtime.go:1411 +0x10d
github.com/loadimpact/k6/js.(*VU).runFn(0xc420de0510, 0xe8ff80, 0xc421a11c80, 0xc4218fff20, 0xc420b21b00, 0xc422d83de0, 0x1, 0x1, 0xc4201a9380, 0xc420548240, ...)
	/home/user/go/src/github.com/loadimpact/k6/js/runner.go:415 +0x3a8
github.com/loadimpact/k6/js.(*Runner).runPart(0xc4229e3720, 0xe8ff80, 0xc421a11c80, 0xc422e56720, 0xd15e36, 0x5, 0x0, 0x0, 0x0, 0x0, ...)
	/home/user/go/src/github.com/loadimpact/k6/js/runner.go:299 +0x2a1
github.com/loadimpact/k6/js.(*Runner).Setup(0xc4229e3720, 0xe8ff80, 0xc42273a040, 0xc422e56720, 0x0, 0x0)
	/home/user/go/src/github.com/loadimpact/k6/js/runner.go:208 +0xf0
github.com/loadimpact/k6/core/local.(*Executor).Run(0xc420b2eea0, 0xe8ff80, 0xc42273a040, 0xc422e56720, 0x0, 0x0)
	/home/user/go/src/github.com/loadimpact/k6/core/local/local.go:157 +0x1304
github.com/loadimpact/k6/core.(*Engine).Run.func4(0xc4204e4008, 0xc4207f78c0, 0xe8ff80, 0xc42273a040, 0xc422cc4020)
	/home/user/go/src/github.com/loadimpact/k6/core/engine.go:183 +0x58
created by github.com/loadimpact/k6/core.(*Engine).Run
	/home/user/go/src/github.com/loadimpact/k6/core/engine.go:182 +0x871
```

while `return { arr: typedArr };` will also panic in the same way, because we marshal the setup data to JSON before passing it to the VUs:
```
panic: Cannot export valueProperty

goroutine 52 [running]:
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*valueProperty).Export(0xc422ad1ce0, 0x1, 0xe96ca0)
	/home/user/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/value.go:478 +0x39
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*baseObject).export(0xc422f48f00, 0xc422f53260, 0x0)
	/home/user/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/object.go:517 +0x1a1
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*Object).Export(0xc422f53260, 0x3, 0xe96b60)
	/home/user/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/value.go:700 +0x34
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*baseObject).export(0xc422f494a0, 0x1505940, 0xe97100)
	/home/user/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/object.go:517 +0x1a1
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*Object).Export(0xc422f538a0, 0xe8ff80, 0xc422f3fc80)
	/home/user/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/value.go:700 +0x34
github.com/loadimpact/k6/js.(*Runner).Setup(0xc423116140, 0xe8ff80, 0xc421046040, 0xc420fe6b40, 0x0, 0x0)
	/home/user/go/src/github.com/loadimpact/k6/js/runner.go:218 +0x185
github.com/loadimpact/k6/core/local.(*Executor).Run(0xc42066ca20, 0xe8ff80, 0xc421046040, 0xc420fe6b40, 0x0, 0x0)
	/home/user/go/src/github.com/loadimpact/k6/core/local/local.go:157 +0x1304
github.com/loadimpact/k6/core.(*Engine).Run.func4(0xc4201dc018, 0xc420a8f8c0, 0xe8ff80, 0xc421046040, 0xc421456020)
	/home/user/go/src/github.com/loadimpact/k6/core/engine.go:183 +0x58
created by github.com/loadimpact/k6/core.(*Engine).Run
	/home/user/go/src/github.com/loadimpact/k6/core/engine.go:182 +0x871
```

As far as I can see, goja supports typed arrays only [partially](https://github.com/dop251/goja/blob/master/builtin_typedarrays.go), maybe, but the [core.js library](https://github.com/zloirock/core-js) we use as a polyfill seems to implement them. Still, goja panicking in this situation seems unreasonable and a bug at first glance

**Comment by cuonglm** [comment]
According to [goja status](https://github.com/dop251/goja#current-status), it does not support typed array at all.

**Comment by MStoykov** [comment]
@cuonglm we still should/must not panic ;) Whether we support them or not :)

**Comment by RoySunnySean007** [comment]
Dear @na-- @MStoykov @cuonglm ,

Regarding this issue, seems goja(https://github.com/dop251/goja#current-status) is not actively developed (there is even no release for this project), will we consider choose another golang JS engine for K6 in order to support typedArray(e.g, []uint8?)

Thanks,
Roy

**Comment by na--** [comment]
@RoySunnySean007, goja is actively maintained and somewhat actively developed, the [`es6` branch](https://github.com/dop251/goja/tree/es6) even has typed arrays since https://github.com/dop251/goja/pull/137... It's still not stable enough for us to use in k6, but I hope it will be soon. 

What's more, switching runtimes is not feasible at this point in time, for the reasons I enumerated in https://github.com/loadimpact/k6/issues/751#issuecomment-417252677. We'd like to have the option to do it, at some point in the future, but we have a lot of refactoring work to do before that :disappointed: And even if we get there, it wouldn't be trivial to switch to something else. There aren't a ton of JS runtimes for Go out there, and integrating a C/C++ runtime like V8, while _probably_ technically possible, has a ton of other associated issues and would be a very big undertaking.

**Comment by RoySunnySean007** [comment]
Thanks @na--  for ur clear explanation! My problem is send binary message(uint8 array, Google protobuf) via K6 ws (https://community.k6.io/t/how-can-send-binary-message-via-websocket-in-k6/635/4).

**Comment by na--** [comment]
@RoySunnySean007, I answered in the forum, but as evident from this issue and https://github.com/loadimpact/k6/issues/1020, binary support is currently somewhat primitive in k6... :disappointed:

**Comment by na--** [comment]
Another array-related example that currently panics goja, even with `--compatibility-mode=base`:
```js
module.exports.default = function () {
    Array.apply(null, Array(1))
}
```

will produce something like:
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x80 pc=0x865e0c]

goroutine 52 [running]:
github.com/loadimpact/k6/vendor/github.com/dop251/goja.AssertFunction.func1.1(0xc0006bfc30)
	/home/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/runtime.go:1489 +0x98
panic(0xd73ba0, 0x1982740)
	/usr/lib/go/src/runtime/panic.go:969 +0x166
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*vm).try.func1(0xc000572270, 0x0, 0xc0006bfb08, 0x0, 0x0, 0x0, 0xc0006bfb80)
	/home/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/vm.go:377 +0x3da
panic(0xd73ba0, 0x1982740)
	/usr/lib/go/src/runtime/panic.go:969 +0x166
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*Runtime).builtin_newArray(0xc000500300, 0xc0004da720, 0x1, 0x1, 0xc0003cece0, 0x19c93c0)
	/home/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/builtin_array.go:13 +0x3c
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*Runtime).constructWrap.func1(0x10e1aa0, 0x19c7540, 0xc0004da720, 0x1, 0x1, 0x1, 0x30)
	/home/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/runtime.go:683 +0x4c
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*Runtime).functionproto_apply(0xc000500300, 0x10e1500, 0xc0003ced00, 0xc000472210, 0x2, 0x9, 0xc0003cece0, 0xc0004a5ba0)
	/home/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/builtin_function.go:59 +0x118
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*vm)._nativeCall(0xc000572270, 0xc0005678c0, 0x2)
	/home/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/vm.go:1795 +0x291
github.com/loadimpact/k6/vendor/github.com/dop251/goja.call.exec(0x2, 0xc000572270)
	/home/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/vm.go:1779 +0x4b5
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*vm).run(0xc000572270)
	/home/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/vm.go:289 +0x99
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*funcObject).Call(0xc0005700c0, 0x10e1b40, 0x19c7540, 0xc0004da6a0, 0x1, 0x1, 0x8, 0x203000)
	/home/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/func.go:154 +0x2cc
github.com/loadimpact/k6/vendor/github.com/dop251/goja.AssertFunction.func1.2()
	/home/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/runtime.go:1494 +0x96
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*vm).try(0xc000572270, 0xc0006d8b98, 0x0)
	/home/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/vm.go:383 +0x132
github.com/loadimpact/k6/vendor/github.com/dop251/goja.AssertFunction.func1(0x10e1b40, 0x19c7540, 0xc0004da6a0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
	/home/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/runtime.go:1493 +0xfc
github.com/loadimpact/k6/js.(*VU).runFn(0xc000557320, 0x10d4ee0, 0xc0004c56b0, 0x1, 0xc000448580, 0xc0004da6a0, 0x1, 0x1, 0xc0000aa440, 0x1e, ...)
	/home/go/src/github.com/loadimpact/k6/js/runner.go:555 +0x14e
github.com/loadimpact/k6/js.(*ActiveVU).RunOnce(0xc0004a5ae0, 0x0, 0x0)
	/home/go/src/github.com/loadimpact/k6/js/runner.go:518 +0x220
github.com/loadimpact/k6/lib/executor.getIterationRunner.func1(0x10d4ea0, 0xc0004f2960, 0x10c1d40, 0xc0004a5ae0, 0xc0004da620)
	/home/go/src/github.com/loadimpact/k6/lib/executor/helpers.go:86 +0x4d
github.com/loadimpact/k6/lib/executor.PerVUIterations.Run.func3(0x10cb2e0, 0xc000557320)
	/home/go/src/github.com/loadimpact/k6/lib/executor/per_vu_iterations.go:227 +0x213
created by github.com/loadimpact/k6/lib/executor.PerVUIterations.Run
	/home/go/src/github.com/loadimpact/k6/lib/executor/per_vu_iterations.go:239 +0xbc0
```

just adding these here so we don't forget them, but we should open goja issues/PRs for them

**Comment by MStoykov** [comment]
Both of the scripts don't panic (and probably work) with branch [es6Update](https://github.com/loadimpact/k6/tree/es6Update), so it looks like those were fixed in the upstream [es6](https://github.com/dop251/goja/tree/es6) branch. 

So I propose we try to upgrade to it for v0.28.0 and test it heavily :D

**Comment by na--** [comment]
This issue was resolved by https://github.com/loadimpact/k6/pull/1588.
